// 3/coursespace-angular/src/app/components/hero/hero.component.ts
import { Component } from '@angular/core';
import { Stat } from '../../models/types';
import { STATS } from '../../data/mock-data';

@Component({
  selector: 'app-hero',
  standalone: false,
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.css']
})
export class HeroComponent {
  stats: Stat[] = STATS;

  scrollToCourses(): void {
    const element = document.getElementById('courses');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  }

  watchVideo(): void {
    console.log('Opening video modal...');
  }
}

<section id="hero" class="min-h-screen pt-20 relative overflow-hidden bg-gradient-to-br from-gray-50 via-white to-primary-50 dark:from-dark-bg dark:via-dark-bg dark:to-gray-900">
  <div class="absolute inset-0 opacity-10">
    <div class="absolute top-20 left-10 w-72 h-72 bg-primary-300 rounded-full mix-blend-multiply filter blur-3xl animate-pulse-slow"></div>
    <div class="absolute top-40 right-10 w-72 h-72 bg-secondary-300 rounded-full mix-blend-multiply filter blur-3xl animate-pulse-slow" style="animation-delay: 1s;"></div>
    <div class="absolute bottom-20 left-1/3 w-72 h-72 bg-accent-300 rounded-full mix-blend-multiply filter blur-3xl animate-pulse-slow" style="animation-delay: 2s;"></div>
  </div>

  <div class="container-custom mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
    <div class="grid lg:grid-cols-2 gap-12 items-center min-h-[calc(100vh-80px)] py-12">
      <div class="space-y-8">
        <div class="inline-flex items-center space-x-2 bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 px-4 py-2 rounded-full text-sm font-medium">
          <span nz-icon nzType="rocket" nzTheme="outline"></span>
          <span>Start Learning Today</span>
        </div>

        <h1 class="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white leading-tight">
          Learn Anytime,
          <br />
          <span class="relative inline-block">
            Anywhere
            <svg class="absolute -bottom-2 left-0 w-full" viewBox="0 0 200 12" fill="none">
              <path d="M2 10C40 2 80 2 100 6C120 10 160 10 198 2" stroke="url(#underline)" stroke-width="4" stroke-linecap="round"/>
              <defs>
                <linearGradient id="underline" x1="0" y1="0" x2="200" y2="0">
                  <stop stop-color="#3b82f6"/>
                  <stop offset="1" stop-color="#22c55e"/>
                </linearGradient>
              </defs>
            </svg>
          </span>
          <br />
          <span class="bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent">
            Upskill Your Career
          </span>
        </h1>

        <p class="text-lg text-gray-600 dark:text-gray-300 max-w-xl leading-relaxed">
          Join thousands of students worldwide and transform your career with our expert-led online courses. Learn at your own pace with lifetime access.
        </p>

        <div class="flex flex-wrap gap-4">
          <button 
            (click)="scrollToCourses()"
            class="inline-flex items-center space-x-2 bg-gradient-to-r from-primary-600 to-primary-700 hover:from-primary-700 hover:to-primary-800 text-white font-semibold py-4 px-8 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 active:scale-95"
          >
            <span>Get Started</span>
            <span nz-icon nzType="arrow-right" nzTheme="outline"></span>
          </button>

          <button 
            (click)="watchVideo()"
            class="inline-flex items-center space-x-3 text-gray-700 dark:text-gray-200 font-semibold py-4 px-6 hover:text-primary-600 dark:hover:text-primary-400 transition-colors duration-300"
          >
            <span class="w-12 h-12 bg-white dark:bg-gray-800 rounded-full flex items-center justify-center shadow-lg hover:shadow-xl transition-all duration-300">
              <span nz-icon nzType="play-circle" nzTheme="fill" class="text-primary-600 text-xl"></span>
            </span>
            <span>Watch Video</span>
          </button>
        </div>

        <div class="grid grid-cols-3 gap-6 pt-8 border-t border-gray-200 dark:border-gray-800">
          @for (stat of stats; track stat.id) {
            <div class="text-center">
              <div class="text-3xl sm:text-4xl font-bold bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent">
                {{ stat.value }}
              </div>
              <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">
                {{ stat.label }}
              </div>
            </div>
          }
        </div>
      </div>

      <div class="relative lg:pl-12">
        <div class="relative">
          <img 
            src="https://picsum.photos/seed/hero-main/600/500" 
            alt="Online Learning"
            class="w-full rounded-3xl shadow-2xl"
          />
          
          <div class="absolute -top-4 -left-4 sm:-left-8 bg-white dark:bg-gray-800 rounded-2xl p-4 shadow-xl flex items-center space-x-3 animate-fade-in">
            <div class="w-12 h-12 bg-secondary-100 dark:bg-secondary-900/30 rounded-xl flex items-center justify-center">
              <span nz-icon nzType="trophy" nzTheme="fill" class="text-secondary-600 text-xl"></span>
            </div>
            <div>
              <div class="font-semibold text-gray-900 dark:text-white">Award Winner</div>
              <div class="text-sm text-gray-500 dark:text-gray-400">2024 Best Platform</div>
            </div>
          </div>

          <div class="absolute -bottom-4 -right-4 sm:-right-8 bg-white dark:bg-gray-800 rounded-2xl p-4 shadow-xl flex items-center space-x-3">
            <div class="w-12 h-12 bg-primary-100 dark:bg-primary-900/30 rounded-xl flex items-center justify-center">
              <span nz-icon nzType="star" nzTheme="fill" class="text-primary-600 text-xl"></span>
            </div>
            <div>
              <div class="font-semibold text-gray-900 dark:text-white">4.9/5 Rating</div>
              <div class="text-sm text-gray-500 dark:text-gray-400">15,000+ Reviews</div>
            </div>
          </div>

          <div class="absolute top-1/2 -right-2 sm:-right-6 transform -translate-y-1/2">
            <div class="bg-white dark:bg-gray-800 rounded-2xl p-4 shadow-xl w-40">
              <div class="flex items-center justify-center space-x-1 mb-2">
                <span nz-icon nzType="check-circle" nzTheme="fill" class="text-secondary-500"></span>
                <span class="text-xs text-gray-600 dark:text-gray-400">Certified Courses</span>
              </div>
              <div class="flex -space-x-2">
                <div class="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 border-2 border-white dark:border-gray-800 overflow-hidden">
                  <img src="https://picsum.photos/seed/cert1/40/40" alt="Certificate" class="w-full h-full object-cover">
                </div>
                <div class="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 border-2 border-white dark:border-gray-800 overflow-hidden">
                  <img src="https://picsum.photos/seed/cert2/40/40" alt="Certificate" class="w-full h-full object-cover">
                </div>
                <div class="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 border-2 border-white dark:border-gray-800 overflow-hidden">
                  <img src="https://picsum.photos/seed/cert3/40/40" alt="Certificate" class="w-full h-full object-cover">
                </div>
                <div class="w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-900/30 border-2 border-white dark:border-gray-800 flex items-center justify-center">
                  <span class="text-xs font-semibold text-primary-600">+50</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// vinyl-vibe/src/components/Hero.tsx
import React from 'react';
import { heroData } from '../mock';

const WaveSVG: React.FC<{ className?: string }> = ({ className }) => (
  <svg
    className={className}
    viewBox="0 0 1440 120"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    preserveAspectRatio="none"
  >
    <path
      d="M0 32L48 37.3C96 43 192 53 288 58.7C384 64 480 64 576 58.7C672 53 768 43 864 42.7C960 43 1056 53 1152 58.7C1248 64 1344 64 1392 64L1440 64V120H1392C1344 120 1248 120 1152 120C1056 120 960 120 864 120C768 120 672 120 576 120C480 120 384 120 288 120C192 120 96 120 48 120H0V32Z"
      fill="url(#wave-gradient)"
      fillOpacity="0.3"
    />
    <defs>
      <linearGradient id="wave-gradient" x1="0" y1="0" x2="1440" y2="0">
        <stop stopColor="#8B5CF6" />
        <stop offset="0.5" stopColor="#EC4899" />
        <stop offset="1" stopColor="#8B5CF6" />
      </linearGradient>
    </defs>
  </svg>
);

const AnimatedWave: React.FC = () => (
  <div className="absolute inset-0 overflow-hidden pointer-events-none">
    <div className="absolute bottom-0 left-0 right-0">
      <WaveSVG className="w-full h-24 animate-pulse" />
    </div>
    <div className="absolute bottom-0 left-0 right-0">
      <svg
        className="w-full h-32 opacity-20"
        viewBox="0 0 1440 320"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M0 192L60 176C120 160 240 128 360 133.3C480 139 600 181 720 202.7C840 224 960 224 1080 213.3C1200 203 1320 181 1380 170.7L1440 160V320H1380C1320 320 1200 320 1080 320C960 320 840 320 720 320C600 320 480 320 360 320C240 320 120 320 60 320H0V192Z"
          fill="url(#wave-gradient-2)"
        />
        <defs>
          <linearGradient id="wave-gradient-2" x1="0" y1="0" x2="1440" y2="0">
            <stop stopColor="#EC4899" />
            <stop offset="0.5" stopColor="#8B5CF6" />
            <stop offset="1" stopColor="#EC4899" />
          </linearGradient>
        </defs>
      </svg>
    </div>

    <div className="absolute top-1/4 left-1/4 transform -translate-x-1/2 -translate-y-1/2">
      <div className="flex items-end space-x-1 h-16">
        {[1, 2, 3, 4, 5, 6, 7].map((i) => (
          <div
            key={i}
            className="w-2 bg-gradient-to-t from-purple-500 to-pink-500 rounded-full animate-bounce"
            style={{
              height: `${20 + i * 8}px`,
              animationDelay: `${i * 0.1}s`,
              animationDuration: '1s'
            }}
          />
        ))}
      </div>
    </div>

    <div className="absolute bottom-1/3 right-1/4 transform translate-x-1/2">
      <div className="flex items-end space-x-1 h-12">
        {[1, 2, 3, 4, 5, 6].map((i) => (
          <div
            key={i}
            className="w-1.5 bg-gradient-to-t from-pink-500 to-purple-500 rounded-full animate-pulse"
            style={{
              height: `${15 + (7 - i) * 6}px`,
              animationDelay: `${i * 0.15}s`
            }}
          />
        ))}
      </div>
    </div>
  </div>
);

const Hero: React.FC = () => {
  const { title, subtitle, ctaPrimary, ctaSecondary } = heroData;

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
      <div className="absolute inset-0">
        <div className="absolute inset-0 bg-gradient-to-br from-purple-900/20 via-transparent to-pink-900/20" />
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-pink-500/10 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '0.5s' }} />
      </div>

      <AnimatedWave />

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-32">
        <div className="text-center">
          <div className="inline-flex items-center px-4 py-2 bg-gray-800/50 border border-gray-700/50 rounded-full mb-8 backdrop-blur-sm">
            <span className="w-2 h-2 bg-purple-400 rounded-full animate-pulse mr-2" />
            <span className="text-sm text-gray-300">探索音乐的无限可能</span>
          </div>

          <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-extrabold mb-6">
            <span className="block text-white">{title.split('')[0]}</span>
            <span className="block bg-gradient-to-r from-purple-400 via-pink-400 to-purple-400 bg-clip-text text-transparent animate-pulse" style={{ animationDuration: '3s' }}>
              {title.slice(1)}
            </span>
          </h1>

          <p className="text-lg sm:text-xl text-gray-400 max-w-2xl mx-auto mb-10 leading-relaxed">
            {subtitle}
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <button className="group relative px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 rounded-xl font-semibold text-white overflow-hidden transition-all duration-300 hover:scale-105 hover:shadow-2xl hover:shadow-purple-500/25">
              <span className="relative z-10 flex items-center">
                {ctaPrimary}
                <svg
                  className="w-5 h-5 ml-2 transform group-hover:translate-x-1 transition-transform"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
              </span>
              <div className="absolute inset-0 bg-gradient-to-r from-pink-600 to-purple-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
            </button>

            <button className="group px-8 py-4 border-2 border-gray-600 rounded-xl font-semibold text-gray-300 transition-all duration-300 hover:border-purple-500 hover:text-white hover:bg-gray-800/50">
              <span className="flex items-center">
                {ctaSecondary}
                <svg
                  className="w-5 h-5 ml-2 transform group-hover:translate-y-0.5 transition-transform"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
                </svg>
              </span>
            </button>
          </div>

          <div className="mt-16 grid grid-cols-3 gap-8 max-w-lg mx-auto">
            <div className="text-center">
              <div className="text-2xl sm:text-3xl font-bold text-white">50K+</div>
              <div className="text-sm text-gray-500 mt-1">精选唱片</div>
            </div>
            <div className="text-center border-x border-gray-700">
              <div className="text-2xl sm:text-3xl font-bold text-white">100+</div>
              <div className="text-sm text-gray-500 mt-1">品牌合作</div>
            </div>
            <div className="text-center">
              <div className="text-2xl sm:text-3xl font-bold text-white">24/7</div>
              <div className="text-sm text-gray-500 mt-1">在线客服</div>
            </div>
          </div>
        </div>
      </div>

      <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
        <svg
          className="w-6 h-6 text-gray-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
        </svg>
      </div>
    </section>
  );
};

export default Hero;
