// personal-portfolio/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SocialLink } from '../../types';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer id="contact" class="footer">
      <!-- Contact Section -->
      <div class="bg-gradient-to-br from-primary-900 to-secondary-900 py-20">
        <div class="container mx-auto px-4">
          <div class="text-center mb-12">
            <span class="tag mb-4 inline-block bg-white/10 text-white">Get In Touch</span>
            <h2 class="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4">Let's Work Together</h2>
            <p class="text-lg text-primary-200 max-w-2xl mx-auto">
              Have a project in mind or want to collaborate? Feel free to reach out!
            </p>
          </div>

          <div class="max-w-3xl mx-auto">
            <!-- Contact Cards -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
              <!-- Email -->
              <a 
                href="mailto:hello@example.com"
                class="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8 text-center hover:bg-white/10 transition-all duration-300 group"
              >
                <div class="w-16 h-16 bg-primary-500/20 rounded-full flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform">
                  <i class="pi pi-envelope text-3xl text-primary-400"></i>
                </div>
                <h3 class="text-white font-semibold text-lg mb-2">Email Me</h3>
                <p class="text-primary-200">{{ email }}</p>
              </a>

              <!-- Location -->
              <div class="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8 text-center">
                <div class="w-16 h-16 bg-primary-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                  <i class="pi pi-map-marker text-3xl text-primary-400"></i>
                </div>
                <h3 class="text-white font-semibold text-lg mb-2">Location</h3>
                <p class="text-primary-200">San Francisco, CA</p>
              </div>
            </div>

            <!-- Social Links -->
            <div class="text-center">
              <p class="text-primary-200 mb-6">Or find me on social media</p>
              <div class="flex items-center justify-center space-x-4">
                @for (link of socialLinks; track link.name) {
                  <a 
                    [href]="link.url" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    class="social-icon"
                    [title]="link.name"
                  >
                    <i [class]="link.icon" class="text-xl"></i>
                  </a>
                }
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Bottom Footer -->
      <div class="border-t border-white/10 py-8">
        <div class="container mx-auto px-4">
          <div class="flex flex-col md:flex-row items-center justify-between">
            <!-- Copyright -->
            <p class="text-primary-300 text-sm mb-4 md:mb-0">
              &copy; {{ currentYear }} John Developer. All rights reserved.
            </p>

            <!-- Quick Links -->
            <div class="flex items-center space-x-6">
              <a href="#hero" class="footer-link text-sm hover:underline">Home</a>
              <a href="#skills" class="footer-link text-sm hover:underline">Skills</a>
              <a href="#projects" class="footer-link text-sm hover:underline">Projects</a>
              <a href="#contact" class="footer-link text-sm hover:underline">Contact</a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  `,
  styles: []
})
export class FooterComponent implements OnInit {
  currentYear = new Date().getFullYear();
  email = 'hello@example.com';
  
  socialLinks: SocialLink[] = [
    { name: 'GitHub', icon: 'pi pi-github', url: 'https://github.com' },
    { name: 'LinkedIn', icon: 'pi pi-linkedin', url: 'https://linkedin.com' },
    { name: 'Twitter', icon: 'pi pi-twitter', url: 'https://twitter.com' },
    { name: 'Dribbble', icon: 'pi pi-palette', url: 'https://dribbble.com' },
    { name: 'Instagram', icon: 'pi pi-instagram', url: 'https://instagram.com' }
  ];

  ngOnInit(): void {}
}

// samet-portfolio/src/components/Footer.tsx
import React from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { Github, Linkedin, Twitter, Mail, Heart } from 'lucide-react';

const Footer: React.FC = () => {
  const { language } = useLanguage();
  const currentYear = new Date().getFullYear();

  const socialLinks = [
    { icon: <Github size={20} />, href: 'https://github.com/sametsoysal', label: 'GitHub' },
    { icon: <Linkedin size={20} />, href: 'https://linkedin.com/in/sametsoysal', label: 'LinkedIn' },
    { icon: <Twitter size={20} />, href: 'https://twitter.com/sametsoysal', label: 'Twitter' },
    { icon: <Mail size={20} />, href: 'mailto:contact@sametsoysal.com', label: 'Email' }
  ];

  return (
    <footer className="py-12 px-4 border-t border-white/10">
      <div className="max-w-6xl mx-auto">
        <div className="grid md:grid-cols-3 gap-8 mb-8">
          {/* Brand */}
          <div>
            <h3 className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent mb-4">
              Samet Soysal
            </h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              {language === 'en'
                ? 'Full Stack Developer passionate about creating beautiful and functional web applications.'
                : 'Güzel ve işlevsel web uygulamaları oluşturmak için tutkulu Full Stack Geliştirici.'}
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="text-white font-semibold mb-4">
              {language === 'en' ? 'Quick Links' : 'Hızlı Bağlantılar'}
            </h4>
            <ul className="space-y-2">
              {['about', 'experience', 'projects', 'skills', 'contact'].map((section) => (
                <li key={section}>
                  <a
                    href={`#${section}`}
                    className="text-gray-400 hover:text-white transition-colors text-sm"
                  >
                    {section.charAt(0).toUpperCase() + section.slice(1)}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Social Links */}
          <div>
            <h4 className="text-white font-semibold mb-4">
              {language === 'en' ? 'Connect' : 'Bağlantı'}
            </h4>
            <div className="flex gap-3">
              {socialLinks.map((social, index) => (
                <a
                  key={index}
                  href={social.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="p-2.5 bg-white/5 border border-white/10 rounded-lg text-gray-400 hover:text-white hover:bg-white/10 hover:border-white/20 transition-all duration-300"
                  aria-label={social.label}
                >
                  {social.icon}
                </a>
              ))}
            </div>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="pt-8 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-gray-500 text-sm">
            © {currentYear} Samet Soysal. All rights reserved.
          </p>
          <p className="text-gray-500 text-sm flex items-center gap-1">
            {language === 'en' ? 'Made with' : 'İle yapıldı'}
            <Heart size={14} className="text-red-500 fill-red-500" />
            {language === 'en' ? 'using React & Tailwind CSS' : 'React ve Tailwind CSS kullanılarak'}
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
