// 6/digital-magazine/src/components/Header.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'

const router = useRouter()
const route = useRoute()
const isScrolled = ref(false)
const isMobileMenuOpen = ref(false)

const navItems = [
  { name: '首页', path: '/' },
  { name: '杂志', path: '/magazine' },
  { name: '关于', path: '/about' }
]

const handleScroll = () => {
  isScrolled.value = window.scrollY > 50
}

const toggleMobileMenu = () => {
  isMobileMenuOpen.value = !isMobileMenuOpen.value
}

const navigateTo = (path: string) => {
  isMobileMenuOpen.value = false
  router.push(path)
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<template>
  <header 
    :class="[
      'fixed top-0 left-0 right-0 z-50 transition-all duration-300',
      isScrolled ? 'bg-white/95 backdrop-blur-md shadow-md py-3' : 'bg-transparent py-5'
    ]"
  >
    <div class="max-w-6xl mx-auto px-4">
      <div class="flex justify-between items-center">
        <!-- Logo -->
        <div class="flex items-center cursor-pointer" @click="navigateTo('/')">
          <div class="w-10 h-10 bg-gradient-to-br from-primary-500 to-accent-500 rounded-lg flex items-center justify-center mr-3">
            <span class="text-white font-bold text-xl">M</span>
          </div>
          <span class="text-2xl font-display font-bold" :class="isScrolled ? 'text-gray-800' : 'text-white'">
            Digital <span class="text-primary-500">Magazine</span>
          </span>
        </div>
        
        <!-- Desktop Navigation -->
        <nav class="hidden md:flex items-center space-x-8">
          <a 
            v-for="item in navItems" 
            :key="item.path"
            @click="navigateTo(item.path)"
            :class="[
              'font-medium transition-colors duration-200 cursor-pointer',
              route.path === item.path 
                ? 'text-primary-600 font-semibold' 
                : isScrolled ? 'text-gray-700 hover:text-primary-500' : 'text-white/90 hover:text-white'
            ]"
          >
            {{ item.name }}
          </a>
        </nav>
        
        <!-- Mobile Menu Button -->
        <button 
          class="md:hidden p-2 rounded-lg transition-colors"
          :class="isScrolled ? 'text-gray-700 hover:bg-gray-100' : 'text-white hover:bg-white/10'"
          @click="toggleMobileMenu"
        >
          <svg v-if="!isMobileMenuOpen" class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
          <svg v-else class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
      </div>
      
      <!-- Mobile Menu -->
      <div 
        :class="[
          'md:hidden transition-all duration-300 overflow-hidden',
          isMobileMenuOpen ? 'max-h-64 opacity-100 mt-4' : 'max-h-0 opacity-0'
        ]"
      >
        <nav class="flex flex-col space-y-3 py-4">
          <a 
            v-for="item in navItems" 
            :key="item.path"
            @click="navigateTo(item.path)"
            :class="[
              'font-medium py-2 px-4 rounded-lg transition-colors duration-200 cursor-pointer',
              route.path === item.path 
                ? 'bg-primary-100 text-primary-700' 
                : 'text-gray-700 hover:bg-gray-100'
            ]"
          >
            {{ item.name }}
          </a>
        </nav>
      </div>
    </div>
  </header>
</template>

<style scoped>
</style>

// samet-portfolio/src/components/Header.tsx
import React, { useState, useEffect } from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { useTheme } from '../contexts/ThemeContext';
import { Sun, Moon, Menu, X, Globe } from 'lucide-react';
import VisitorCounter from './VisitorCounter';

const Header: React.FC = () => {
  const { language, setLanguage, t } = useLanguage();
  const { theme, toggleTheme } = useTheme();
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
    setIsMobileMenuOpen(false);
  };

  const navItems = [
    { id: 'about', label: t.nav.about },
    { id: 'experience', label: t.nav.experience },
    { id: 'projects', label: t.nav.projects },
    { id: 'skills', label: t.nav.skills },
    { id: 'contact', label: t.nav.contact },
  ];

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled
          ? 'bg-white/70 dark:bg-black/30 backdrop-blur-lg border-b border-black/10 dark:border-white/10'
          : 'bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <div className="flex-shrink-0">
            <span className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
              SS
            </span>
          </div>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-8">
            {navItems.map((item) => (
              <button
                key={item.id}
                onClick={() => scrollToSection(item.id)}
                className="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-white transition-colors duration-200 text-sm font-medium"
              >
                {item.label}
              </button>
            ))}
          </nav>

          {/* Right side controls */}
          <div className="hidden md:flex items-center space-x-4">
            <VisitorCounter />
            
            {/* Language Toggle */}
            <button
              onClick={() => setLanguage(language === 'en' ? 'tr' : 'en')}
              className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-white hover:bg-white/70 dark:hover:bg-white/20 transition-all duration-200"
            >
              <Globe size={16} />
              <span className="text-sm font-medium">{language.toUpperCase()}</span>
            </button>

            {/* Theme Toggle */}
            <button
              onClick={toggleTheme}
              className="p-2 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-white hover:bg-white/70 dark:hover:bg-white/20 transition-all duration-200"
            >
              {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
            </button>
          </div>

          {/* Mobile menu button */}
          <button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="md:hidden p-2 rounded-lg text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-white"
          >
            {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>
      </div>

      {/* Mobile Menu */}
      {isMobileMenuOpen && (
        <div className="md:hidden bg-white/90 dark:bg-black/80 backdrop-blur-lg border-t border-black/10 dark:border-white/10">
          <div className="px-4 py-4 space-y-3">
            {navItems.map((item) => (
              <button
                key={item.id}
                onClick={() => scrollToSection(item.id)}
                className="block w-full text-left px-4 py-2 text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-white hover:bg-black/5 dark:hover:bg-white/10 rounded-lg transition-colors"
              >
                {item.label}
              </button>
            ))}
            
            <div className="pt-4 border-t border-black/10 dark:border-white/10">
              <div className="flex items-center justify-between mb-4">
                <VisitorCounter />
              </div>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => setLanguage(language === 'en' ? 'tr' : 'en')}
                  className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200"
                >
                  <Globe size={16} />
                  <span className="text-sm">{language.toUpperCase()}</span>
                </button>
                <button
                  onClick={toggleTheme}
                  className="p-2 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200"
                >
                  {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </header>
  );
};

export default Header;
