// 23/rabbit-jiangxi-travel/src/components/Footer.tsx
import { useNavigate } from 'react-router-dom';

export const Footer = () => {
  const navigate = useNavigate();
  const currentYear = new Date().getFullYear();

  const links = [
    { label: '首页', path: '/' },
    { label: '专栏列表', path: '/episodes' },
    { label: '关于我们', path: '/' },
  ];

  const categories = [
    { label: '长图海报', count: 4 },
    { label: '横屏视频', count: 4 },
    { label: 'H5作品', count: 4 },
  ];

  return (
    <footer className="bg-[#1a2e1f] text-white mt-auto">
      <div className="max-w-7xl mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="md:col-span-2">
            <div className="flex items-center gap-2 mb-4">
              <span className="text-3xl">🐰</span>
              <span className="font-serif-sc text-2xl font-bold">小兔子江西游记</span>
            </div>
            <p className="text-gray-300 mb-4 leading-relaxed">
              跟随小兔子的脚步，探索江西的山水湖林、特色美食、非物质文化遗产和古建筑。
              物华天宝，人杰地灵，感受江西深厚的文化底蕴与良好生态。
            </p>
            <div className="flex gap-4">
              <a href="#" className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors">
                <i className="pi pi-weibo text-lg"></i>
              </a>
              <a href="#" className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors">
                <i className="pi pi-wechat text-lg"></i>
              </a>
              <a href="#" className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors">
                <i className="pi pi-youtube text-lg"></i>
              </a>
            </div>
          </div>

          <div>
            <h3 className="font-serif-sc text-lg font-semibold mb-4">快速链接</h3>
            <ul className="space-y-3">
              {links.map((link, index) => (
                <li key={index}>
                  <button
                    onClick={() => navigate(link.path)}
                    className="text-gray-300 hover:text-white transition-colors flex items-center gap-2"
                  >
                    <i className="pi pi-angle-right text-sm"></i>
                    {link.label}
                  </button>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h3 className="font-serif-sc text-lg font-semibold mb-4">内容分类</h3>
            <ul className="space-y-3">
              {categories.map((cat, index) => (
                <li key={index}>
                  <button
                    onClick={() => navigate('/episodes')}
                    className="text-gray-300 hover:text-white transition-colors flex items-center justify-between w-full"
                  >
                    <span className="flex items-center gap-2">
                      <i className="pi pi-angle-right text-sm"></i>
                      {cat.label}
                    </span>
                    <span className="text-sm bg-white/10 px-2 py-0.5 rounded">{cat.count}期</span>
                  </button>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="border-t border-white/10 mt-10 pt-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-gray-400 text-sm">
            © {currentYear} 小兔子江西游记. All rights reserved.
          </p>
          <div className="flex gap-6 text-sm text-gray-400">
            <a href="#" className="hover:text-white transition-colors">隐私政策</a>
            <a href="#" className="hover:text-white transition-colors">使用条款</a>
            <a href="#" className="hover:text-white transition-colors">联系我们</a>
          </div>
        </div>
      </div>
    </footer>
  );
};

// 8/safe-haven/src/components/Footer.vue
<script setup>
import { useRouter } from 'vue-router'

const router = useRouter()

const quickLinks = [
  { name: '首页', path: '/' },
  { name: '专业指导', path: '/professionals' },
  { name: '自助工具', path: '/tools' },
  { name: '社区交流', path: '/community' },
  { name: '家长资源', path: '/parents' }
]

const resources = [
  { name: '紧急求助', path: '#' },
  { name: '隐私政策', path: '#' },
  { name: '使用条款', path: '#' },
  { name: '常见问题', path: '#' },
  { name: '联系我们', path: '#' }
]

const navigateTo = (path) => {
  if (path.startsWith('/')) {
    router.push(path)
  }
}
</script>

<template>
  <footer class="bg-gray-900 text-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- Brand -->
        <div class="col-span-1 md:col-span-1">
          <div class="flex items-center gap-2 mb-4">
            <span class="text-3xl">🌻</span>
            <span class="text-xl font-bold">SafeHaven</span>
          </div>
          <p class="text-gray-400 text-sm leading-relaxed">
            一个为儿童和青少年提供心理支持的安全港湾，帮助他们建立信心，培养社交技能，找到真正的友谊。
          </p>
          <div class="flex gap-4 mt-6">
            <a href="#" class="text-gray-400 hover:text-white transition-colors">
              <span class="text-xl">📱</span>
            </a>
            <a href="#" class="text-gray-400 hover:text-white transition-colors">
              <span class="text-xl">💬</span>
            </a>
            <a href="#" class="text-gray-400 hover:text-white transition-colors">
              <span class="text-xl">📧</span>
            </a>
          </div>
        </div>

        <!-- Quick Links -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-primary-400">快速链接</h3>
          <ul class="space-y-3">
            <li v-for="link in quickLinks" :key="link.path">
              <a
                @click="navigateTo(link.path)"
                class="text-gray-400 hover:text-white transition-colors cursor-pointer"
              >
                {{ link.name }}
              </a>
            </li>
          </ul>
        </div>

        <!-- Resources -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-primary-400">资源中心</h3>
          <ul class="space-y-3">
            <li v-for="link in resources" :key="link.path">
              <a
                @click="navigateTo(link.path)"
                class="text-gray-400 hover:text-white transition-colors cursor-pointer"
              >
                {{ link.name }}
              </a>
            </li>
          </ul>
        </div>

        <!-- Contact -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-primary-400">联系我们</h3>
          <div class="space-y-3">
            <div class="flex items-center gap-2 text-gray-400">
              <span>📞</span>
              <span>400-888-9999</span>
            </div>
            <div class="flex items-center gap-2 text-gray-400">
              <span>📧</span>
              <span>support@safehaven.com</span>
            </div>
            <div class="flex items-center gap-2 text-gray-400">
              <span>⏰</span>
              <span>每天 9:00 - 21:00</span>
            </div>
          </div>
          
          <!-- Emergency Button -->
          <div class="mt-6">
            <a
              href="#"
              class="inline-block bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium transition-colors"
            >
              🆘 紧急求助
            </a>
          </div>
        </div>
      </div>

      <!-- Bottom Bar -->
      <div class="border-t border-gray-800 mt-12 pt-8">
        <div class="flex flex-col md:flex-row justify-between items-center gap-4">
          <p class="text-gray-500 text-sm">
            © 2024 SafeHaven. 保留所有权利。
          </p>
          <div class="flex items-center gap-2 text-gray-500 text-sm">
            <span>🏆</span>
            <span>中国心理学会认证合作平台</span>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>
