// 14/concert-ticketing-system/src/components/Footer.tsx
import { Link } from 'react-router-dom'

const Footer = () => {
  return (
    <footer className="bg-text-primary text-surface pt-12 pb-6">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 pb-8 border-b border-gray-700">
          {/* Brand Column */}
          <div className="col-span-1 md:col-span-1">
            <Link to="/" className="flex items-center space-x-2 mb-4">
              <i className="pi pi-music text-2xl text-primary"></i>
              <span className="text-xl font-bold">音乐会票务</span>
            </Link>
            <p className="text-gray-400 text-sm">
              为您提供最优质的音乐会票务服务，让每一场演出都成为难忘的回忆。
            </p>
            <div className="flex space-x-4 mt-4">
              <a href="#" className="text-gray-400 hover:text-primary transition-colors">
                <i className="pi pi-facebook text-xl"></i>
              </a>
              <a href="#" className="text-gray-400 hover:text-primary transition-colors">
                <i className="pi pi-twitter text-xl"></i>
              </a>
              <a href="#" className="text-gray-400 hover:text-primary transition-colors">
                <i className="pi pi-instagram text-xl"></i>
              </a>
              <a href="#" className="text-gray-400 hover:text-primary transition-colors">
                <i className="pi pi-youtube text-xl"></i>
              </a>
            </div>
          </div>

          {/* Quick Links */}
          <div>
            <h3 className="text-lg font-semibold mb-4">快速链接</h3>
            <ul className="space-y-2">
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  首页
                </Link>
              </li>
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  演出列表
                </Link>
              </li>
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  热门场馆
                </Link>
              </li>
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  特别活动
                </Link>
              </li>
            </ul>
          </div>

          {/* Support */}
          <div>
            <h3 className="text-lg font-semibold mb-4">客户支持</h3>
            <ul className="space-y-2">
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  帮助中心
                </Link>
              </li>
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  联系我们
                </Link>
              </li>
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  退票政策
                </Link>
              </li>
              <li>
                <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
                  常见问题
                </Link>
              </li>
            </ul>
          </div>

          {/* Contact */}
          <div>
            <h3 className="text-lg font-semibold mb-4">联系我们</h3>
            <ul className="space-y-2">
              <li className="flex items-center space-x-2 text-gray-400 text-sm">
                <i className="pi pi-map-marker"></i>
                <span>北京市朝阳区音乐厅路88号</span>
              </li>
              <li className="flex items-center space-x-2 text-gray-400 text-sm">
                <i className="pi pi-phone"></i>
                <span>400-888-8888</span>
              </li>
              <li className="flex items-center space-x-2 text-gray-400 text-sm">
                <i className="pi pi-envelope"></i>
                <span>support@concert-ticket.com</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="pt-6 flex flex-col md:flex-row justify-between items-center">
          <p className="text-gray-400 text-sm">
            © 2026 音乐会票务系统. 保留所有权利.
          </p>
          <div className="flex space-x-6 mt-4 md:mt-0">
            <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
              隐私政策
            </Link>
            <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
              服务条款
            </Link>
            <Link to="/" className="text-gray-400 hover:text-primary transition-colors text-sm">
              Cookie 政策
            </Link>
          </div>
        </div>
      </div>
    </footer>
  )
}

export default Footer

// 8/safe-haven/src/components/Footer.vue
<script setup>
import { useRouter } from 'vue-router'

const router = useRouter()

const quickLinks = [
  { name: '首页', path: '/' },
  { name: '专业指导', path: '/professionals' },
  { name: '自助工具', path: '/tools' },
  { name: '社区交流', path: '/community' },
  { name: '家长资源', path: '/parents' }
]

const resources = [
  { name: '紧急求助', path: '#' },
  { name: '隐私政策', path: '#' },
  { name: '使用条款', path: '#' },
  { name: '常见问题', path: '#' },
  { name: '联系我们', path: '#' }
]

const navigateTo = (path) => {
  if (path.startsWith('/')) {
    router.push(path)
  }
}
</script>

<template>
  <footer class="bg-gray-900 text-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- Brand -->
        <div class="col-span-1 md:col-span-1">
          <div class="flex items-center gap-2 mb-4">
            <span class="text-3xl">🌻</span>
            <span class="text-xl font-bold">SafeHaven</span>
          </div>
          <p class="text-gray-400 text-sm leading-relaxed">
            一个为儿童和青少年提供心理支持的安全港湾，帮助他们建立信心，培养社交技能，找到真正的友谊。
          </p>
          <div class="flex gap-4 mt-6">
            <a href="#" class="text-gray-400 hover:text-white transition-colors">
              <span class="text-xl">📱</span>
            </a>
            <a href="#" class="text-gray-400 hover:text-white transition-colors">
              <span class="text-xl">💬</span>
            </a>
            <a href="#" class="text-gray-400 hover:text-white transition-colors">
              <span class="text-xl">📧</span>
            </a>
          </div>
        </div>

        <!-- Quick Links -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-primary-400">快速链接</h3>
          <ul class="space-y-3">
            <li v-for="link in quickLinks" :key="link.path">
              <a
                @click="navigateTo(link.path)"
                class="text-gray-400 hover:text-white transition-colors cursor-pointer"
              >
                {{ link.name }}
              </a>
            </li>
          </ul>
        </div>

        <!-- Resources -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-primary-400">资源中心</h3>
          <ul class="space-y-3">
            <li v-for="link in resources" :key="link.path">
              <a
                @click="navigateTo(link.path)"
                class="text-gray-400 hover:text-white transition-colors cursor-pointer"
              >
                {{ link.name }}
              </a>
            </li>
          </ul>
        </div>

        <!-- Contact -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-primary-400">联系我们</h3>
          <div class="space-y-3">
            <div class="flex items-center gap-2 text-gray-400">
              <span>📞</span>
              <span>400-888-9999</span>
            </div>
            <div class="flex items-center gap-2 text-gray-400">
              <span>📧</span>
              <span>support@safehaven.com</span>
            </div>
            <div class="flex items-center gap-2 text-gray-400">
              <span>⏰</span>
              <span>每天 9:00 - 21:00</span>
            </div>
          </div>
          
          <!-- Emergency Button -->
          <div class="mt-6">
            <a
              href="#"
              class="inline-block bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium transition-colors"
            >
              🆘 紧急求助
            </a>
          </div>
        </div>
      </div>

      <!-- Bottom Bar -->
      <div class="border-t border-gray-800 mt-12 pt-8">
        <div class="flex flex-col md:flex-row justify-between items-center gap-4">
          <p class="text-gray-500 text-sm">
            © 2024 SafeHaven. 保留所有权利。
          </p>
          <div class="flex items-center gap-2 text-gray-500 text-sm">
            <span>🏆</span>
            <span>中国心理学会认证合作平台</span>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>
