// 24/survey-app/src/app/components/auth/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatDividerModule } from '@angular/material/divider';
import { AuthService } from '../../services/auth.service';
import { LoginCredentials } from '../../models/user.model';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterLink,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatDividerModule
  ],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  loginForm: FormGroup;
  errorMessage: string = '';
  isLoading: boolean = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]]
    });
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';

    const credentials: LoginCredentials = this.loginForm.value;
    
    this.authService.login(credentials).subscribe({
      next: (user) => {
        this.isLoading = false;
        if (user) {
          this.router.navigate(['/dashboard']);
        } else {
          this.errorMessage = '用户名或密码错误';
        }
      },
      error: () => {
        this.isLoading = false;
        this.errorMessage = '登录时发生错误，请重试';
      }
    });
  }

  goToRegister(): void {
    this.router.navigate(['/register']);
  }
}

<div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
  <mat-card class="w-full max-w-md shadow-xl">
    <mat-card-header class="justify-center pb-4">
      <mat-card-title class="text-2xl font-bold text-gray-800">登录系统</mat-card-title>
      <mat-card-subtitle>调查管理系统</mat-card-subtitle>
    </mat-card-header>
    
    <mat-card-content>
      <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-6">
        <div>
          <mat-form-field appearance="fill" class="w-full">
            <mat-label>用户名</mat-label>
            <input matInput formControlName="username" placeholder="请输入用户名">
            <mat-icon matSuffix>person</mat-icon>
            @if (loginForm.get('username')?.invalid && loginForm.get('username')?.touched) {
              <mat-error>用户名不能为空</mat-error>
            }
          </mat-form-field>
        </div>
        
        <div>
          <mat-form-field appearance="fill" class="w-full">
            <mat-label>密码</mat-label>
            <input matInput formControlName="password" type="password" placeholder="请输入密码">
            <mat-icon matSuffix>lock</mat-icon>
            @if (loginForm.get('password')?.invalid && loginForm.get('password')?.touched) {
              <mat-error>密码不能为空</mat-error>
            }
          </mat-form-field>
        </div>
        
        @if (errorMessage) {
          <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg flex items-center">
            <mat-icon class="mr-2">error</mat-icon>
            <span>{{ errorMessage }}</span>
          </div>
        }
        
        <button 
          mat-raised-button 
          color="primary" 
          type="submit" 
          class="w-full py-3 text-lg font-medium"
          [disabled]="loginForm.invalid || isLoading"
        >
          @if (isLoading) {
            <mat-spinner diameter="20" class="mr-2"></mat-spinner>
          }
          {{ isLoading ? '登录中...' : '登 录' }}
        </button>
      </form>
      
      <div class="mt-6 text-center">
        <p class="text-gray-600">
          还没有账户？
          <button mat-button color="primary" (click)="goToRegister()" class="font-medium">
            立即注册
          </button>
        </p>
      </div>
      
      <mat-divider class="my-6"></mat-divider>
      
      <div class="bg-blue-50 rounded-lg p-4">
        <h4 class="font-medium text-blue-800 mb-2">测试账户：</h4>
        <p class="text-sm text-blue-700">
          <strong>管理员：</strong>用户名: admin / 密码: admin123
        </p>
      </div>
    </mat-card-content>
  </mat-card>
</div>

// 12/game-vote-app/src/views/Login.vue
<template>
  <div class="min-h-[calc(100vh-120px)] flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 py-10">
    <el-card class="w-full max-w-md shadow-2xl">
      <template #header>
        <div class="text-center">
          <el-icon class="text-blue-600 mb-2" :size="48">
            <User />
          </el-icon>
          <h2 class="text-2xl font-bold text-gray-800">用户登录</h2>
          <p class="text-gray-500 text-sm mt-1">登录以参与游戏投票</p>
        </div>
      </template>
      
      <el-form 
        ref="formRef" 
        :model="loginForm" 
        :rules="rules" 
        label-position="top"
        @submit.prevent="handleLogin"
      >
        <el-form-item label="用户名" prop="username">
          <el-input 
            v-model="loginForm.username" 
            placeholder="请输入用户名"
            prefix-icon="User"
            size="large"
          />
        </el-form-item>
        
        <el-form-item label="密码" prop="password">
          <el-input 
            v-model="loginForm.password" 
            type="password"
            placeholder="请输入密码"
            prefix-icon="Lock"
            size="large"
            show-password
            @keyup.enter="handleLogin"
          />
        </el-form-item>
        
        <el-form-item>
          <el-button 
            type="primary" 
            size="large" 
            :loading="loading" 
            class="w-full h-12 text-lg"
            @click="handleLogin"
          >
            登录
          </el-button>
        </el-form-item>
      </el-form>
      
      <div class="text-center text-gray-500">
        <span>还没有账号？</span>
        <router-link to="/register" class="text-blue-600 hover:text-blue-800 font-medium">
          立即注册
        </router-link>
      </div>
      
      <el-divider>演示账号</el-divider>
      <div class="bg-gray-50 p-4 rounded-lg text-sm text-gray-600">
        <p><strong>管理员：</strong> admin / 123456</p>
        <p><strong>普通用户：</strong> game_lover / 123456</p>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { useAuthStore } from '@/stores/auth'
import { useGameStore } from '@/stores/game'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()
const gameStore = useGameStore()

const formRef = ref<FormInstance>()
const loading = ref(false)

interface LoginForm {
  username: string
  password: string
}

const loginForm = reactive<LoginForm>({
  username: '',
  password: ''
})

const rules: FormRules = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' }
  ]
}

onMounted(() => {
  gameStore.loadData()
  authStore.loadUser()
  if (authStore.isLoggedIn) {
    router.push('/')
  }
})

const handleLogin = async () => {
  if (!formRef.value) return
  
  await formRef.value.validate((valid) => {
    if (valid) {
      loading.value = true
      
      setTimeout(() => {
        const user = gameStore.findUser(loginForm.username, loginForm.password)
        
        if (user) {
          authStore.login(user)
          ElMessage.success('登录成功！')
          
          const redirect = route.query.redirect as string
          router.push(redirect || '/')
        } else {
          ElMessage.error('用户名或密码错误')
        }
        
        loading.value = false
      }, 500)
    }
  })
}
</script>
