// 3/growmore-website/src/components/Navbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'

const router = useRouter()
const route = useRoute()
const isMenuOpen = ref(false)
const isScrolled = ref(false)

const navLinks = [
  { name: '主页', path: '/' },
  { name: '服务', path: '/services' },
  { name: '关于我们', path: '/about' },
  { name: '联系我们', path: '/contact' }
]

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

const navigateTo = (path: string) => {
  router.push(path)
  isMenuOpen.value = false
}

const handleScroll = () => {
  isScrolled.value = window.scrollY > 20
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<template>
  <nav 
    :class="[
      'fixed top-0 left-0 right-0 z-50 transition-all duration-300',
      isScrolled ? 'bg-white shadow-lg py-3' : 'bg-transparent py-5'
    ]"
  >
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center">
        <div 
          class="flex items-center cursor-pointer"
          @click="navigateTo('/')"
        >
          <div class="w-10 h-10 bg-gradient-to-br from-primary to-secondary rounded-lg flex items-center justify-center">
            <span class="text-white font-bold text-xl">G</span>
          </div>
          <span 
            :class="[
              'ml-3 text-xl font-bold transition-colors duration-300',
              isScrolled ? 'text-text' : 'text-white'
            ]"
          >
            GrowMore Inc.
          </span>
        </div>

        <div class="hidden md:flex items-center space-x-8">
          <a 
            v-for="link in navLinks" 
            :key="link.path"
            @click="navigateTo(link.path)"
            :class="[
              'cursor-pointer font-medium transition-all duration-300 relative',
              route.path === link.path 
                ? (isScrolled ? 'text-primary' : 'text-secondary') 
                : (isScrolled ? 'text-text hover:text-primary' : 'text-white hover:text-secondary'),
              'after:absolute after:bottom-[-4px] after:left-0 after:h-0.5 after:bg-primary after:transition-all after:duration-300',
              route.path === link.path ? 'after:w-full' : 'after:w-0 hover:after:w-full'
            ]"
          >
            {{ link.name }}
          </a>
        </div>

        <button 
          class="md:hidden p-2 rounded-lg transition-colors duration-300"
          :class="isScrolled ? 'hover:bg-gray-100' : 'hover:bg-white/10'"
          @click="toggleMenu"
        >
          <svg 
            :class="['w-6 h-6 transition-colors duration-300', isScrolled ? 'text-text' : 'text-white']"
            fill="none" 
            stroke="currentColor" 
            viewBox="0 0 24 24"
          >
            <path 
              v-if="!isMenuOpen"
              stroke-linecap="round" 
              stroke-linejoin="round" 
              :stroke-width="2" 
              d="M4 6h16M4 12h16M4 18h16"
            />
            <path 
              v-else
              stroke-linecap="round" 
              stroke-linejoin="round" 
              :stroke-width="2" 
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>

      <div 
        v-if="isMenuOpen"
        class="md:hidden mt-4 pb-4 bg-white rounded-xl shadow-xl"
      >
        <div class="flex flex-col space-y-2 px-4 py-2">
          <a 
            v-for="link in navLinks" 
            :key="link.path"
            @click="navigateTo(link.path)"
            :class="[
              'px-4 py-3 rounded-lg cursor-pointer font-medium transition-all duration-200',
              route.path === link.path 
                ? 'bg-primary/10 text-primary' 
                : 'text-text hover:bg-gray-50'
            ]"
          >
            {{ link.name }}
          </a>
        </div>
      </div>
    </div>
  </nav>
</template>

// fleet-alerts-dashboard/src/app/navbar/navbar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  @Input() unreadCount: number = 0;
  @Output() notificationsClick = new EventEmitter<void>();

  onNotificationsClick() {
    this.notificationsClick.emit();
  }
}

<nav class="bg-white border-b border-gray-200 px-6 py-3 shadow-sm">
  <div class="flex items-center justify-between">
    <div class="flex items-center space-x-4">
      <div class="flex items-center space-x-2">
        <div class="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
          <span class="text-white font-bold text-sm">F</span>
        </div>
        <span class="text-lg font-semibold text-gray-800">Fleet Manager</span>
      </div>
      
      <div class="hidden md:flex items-center space-x-6 ml-8">
        <a href="#" class="text-gray-600 hover:text-blue-600 font-medium text-sm">Dashboard</a>
        <a href="#" class="text-gray-600 hover:text-blue-600 font-medium text-sm">Vehicles</a>
        <a href="#" class="text-gray-600 hover:text-blue-600 font-medium text-sm">Drivers</a>
        <a href="#" class="text-gray-600 hover:text-blue-600 font-medium text-sm">Trips</a>
        <a href="#" class="text-gray-600 hover:text-blue-600 font-medium text-sm">Reports</a>
      </div>
    </div>
    
    <div class="flex items-center space-x-4">
      <div class="hidden md:flex items-center bg-gray-100 rounded-lg px-3 py-2">
        <svg class="w-4 h-4 text-gray-400 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
        </svg>
        <input type="text" placeholder="Search..." class="bg-transparent border-none outline-none text-sm text-gray-600 w-48">
      </div>
      
      <button 
        (click)="onNotificationsClick()"
        class="relative p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
      >
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
        </svg>
        <span 
          *ngIf="unreadCount > 0"
          class="absolute -top-0.5 -right-0.5 bg-red-500 text-white text-xs font-medium rounded-full min-w-4 h-4 flex items-center justify-center px-1"
        >
          {{ unreadCount > 9 ? '9+' : unreadCount }}
        </span>
      </button>
      
      <div class="flex items-center space-x-2">
        <div class="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-500 rounded-full flex items-center justify-center">
          <span class="text-white font-medium text-sm">JD</span>
        </div>
        <span class="hidden md:inline text-sm font-medium text-gray-700">John Doe</span>
      </div>
    </div>
  </div>
</nav>
