// samet-portfolio/src/components/Footer.tsx
import React from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { Github, Linkedin, Twitter, Mail, Heart } from 'lucide-react';

const Footer: React.FC = () => {
  const { language } = useLanguage();
  const currentYear = new Date().getFullYear();

  const socialLinks = [
    { icon: <Github size={20} />, href: 'https://github.com/sametsoysal', label: 'GitHub' },
    { icon: <Linkedin size={20} />, href: 'https://linkedin.com/in/sametsoysal', label: 'LinkedIn' },
    { icon: <Twitter size={20} />, href: 'https://twitter.com/sametsoysal', label: 'Twitter' },
    { icon: <Mail size={20} />, href: 'mailto:contact@sametsoysal.com', label: 'Email' }
  ];

  return (
    <footer className="py-12 px-4 border-t border-black/10 dark:border-white/10">
      <div className="max-w-6xl mx-auto">
        <div className="grid md:grid-cols-3 gap-8 mb-8">
          {/* Brand */}
          <div>
            <h3 className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent mb-4">
              Samet Soysal
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              {language === 'en'
                ? 'Full Stack Developer passionate about creating beautiful and functional web applications.'
                : 'Güzel ve işlevsel web uygulamaları oluşturmak için tutkulu Full Stack Geliştirici.'}
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="text-gray-900 dark:text-white font-semibold mb-4">
              {language === 'en' ? 'Quick Links' : 'Hızlı Bağlantılar'}
            </h4>
            <ul className="space-y-2">
              {['about', 'experience', 'projects', 'skills', 'contact'].map((section) => (
                <li key={section}>
                  <a
                    href={`#${section}`}
                    className="text-gray-600 dark:text-gray-400 hover:text-blue-600 dark:hover:text-white transition-colors text-sm"
                  >
                    {section.charAt(0).toUpperCase() + section.slice(1)}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Social Links */}
          <div>
            <h4 className="text-gray-900 dark:text-white font-semibold mb-4">
              {language === 'en' ? 'Connect' : 'Bağlantı'}
            </h4>
            <div className="flex gap-3">
              {socialLinks.map((social, index) => (
                <a
                  key={index}
                  href={social.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="p-2.5 bg-white/70 dark:bg-white/5 border border-black/10 dark:border-white/10 rounded-lg text-gray-600 dark:text-gray-400 hover:text-blue-600 dark:hover:text-white hover:bg-white/90 dark:hover:bg-white/10 hover:border-black/20 dark:hover:border-white/20 transition-all duration-300"
                  aria-label={social.label}
                >
                  {social.icon}
                </a>
              ))}
            </div>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="pt-8 border-t border-black/10 dark:border-white/10 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-gray-500 text-sm">
            © {currentYear} Samet Soysal. All rights reserved.
          </p>
          <p className="text-gray-500 text-sm flex items-center gap-1">
            {language === 'en' ? 'Made with' : 'İle yapıldı'}
            <Heart size={14} className="text-red-500 fill-red-500" />
            {language === 'en' ? 'using React & Tailwind CSS' : 'React ve Tailwind CSS kullanılarak'}
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// 3/coursespace-angular/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { FooterColumn, SocialLink, CompanyInfo } from '../../models/types';
import { FOOTER_COLUMNS, SOCIAL_LINKS, COMPANY_INFO } from '../../data/mock-data';

@Component({
  selector: 'app-footer',
  standalone: false,
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
  columns: FooterColumn[] = FOOTER_COLUMNS;
  socialLinks: SocialLink[] = SOCIAL_LINKS;
  companyInfo: CompanyInfo = COMPANY_INFO;
  currentYear = new Date().getFullYear();

  getSocialIcon(icon: string): string {
    const iconMap: { [key: string]: string } = {
      'instagram': 'instagram',
      'youtube': 'youtube',
      'twitter': 'twitter',
      'dribbble': 'dribbble',
      'github': 'github'
    };
    return iconMap[icon] || 'global';
  }
}

<footer class="bg-gray-900 dark:bg-gray-950 text-white">
  <div class="container-custom mx-auto px-4 sm:px-6 lg:px-8">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 lg:gap-12 py-16">
      <div class="lg:col-span-1">
        <div class="flex items-center space-x-2 mb-6">
          <div class="w-10 h-10 bg-gradient-to-br from-primary-500 to-secondary-500 rounded-xl flex items-center justify-center">
            <span class="text-white font-bold text-xl">C</span>
          </div>
          <span class="text-xl font-bold text-white">{{ companyInfo.name }}</span>
        </div>
        
        <p class="text-gray-400 mb-6 leading-relaxed">
          {{ companyInfo.description }}
        </p>

        <div class="space-y-3">
          <div class="flex items-center space-x-3 text-gray-400">
            <span nz-icon nzType="mail" nzTheme="outline" class="text-primary-400"></span>
            <span class="text-sm">{{ companyInfo.email }}</span>
          </div>
          <div class="flex items-center space-x-3 text-gray-400">
            <span nz-icon nzType="phone" nzTheme="outline" class="text-primary-400"></span>
            <span class="text-sm">{{ companyInfo.phone }}</span>
          </div>
        </div>
      </div>

      @for (column of columns; track column.id) {
        <div>
          <h3 class="text-lg font-semibold text-white mb-6">
            {{ column.title }}
          </h3>
          <ul class="space-y-3">
            @for (link of column.links; track link.id) {
              <li>
                <a 
                  [href]="link.href"
                  class="text-gray-400 hover:text-primary-400 transition-colors duration-200 text-sm flex items-center group"
                >
                  <span nz-icon nzType="right" nzTheme="outline" class="mr-2 opacity-0 group-hover:opacity-100 transform -translate-x-2 group-hover:translate-x-0 transition-all duration-200 text-xs"></span>
                  {{ link.label }}
                </a>
              </li>
            }
          </ul>
        </div>
      }
    </div>

    <div class="border-t border-gray-800 py-8">
      <div class="flex flex-col md:flex-row items-center justify-between gap-6">
        <div class="flex items-center space-x-4">
          <span class="text-gray-400 text-sm">Follow us:</span>
          <div class="flex items-center space-x-3">
            @for (social of socialLinks; track social.id) {
              <a
                [href]="social.url"
                class="w-10 h-10 bg-gray-800 hover:bg-primary-600 rounded-full flex items-center justify-center transition-all duration-300 hover:-translate-y-1 group"
                [nzTooltipTitle]="social.name"
                nz-tooltip
              >
                <span 
                  nz-icon 
                  [nzType]="getSocialIcon(social.icon)" 
                  nzTheme="outline" 
                  class="text-gray-400 group-hover:text-white transition-colors duration-300"
                ></span>
              </a>
            }
          </div>
        </div>

        <div class="text-center md:text-right">
          <p class="text-gray-400 text-sm">
            © {{ currentYear }} {{ companyInfo.name }}. All rights reserved.
          </p>
          <p class="text-gray-500 text-xs mt-1">
            Made with <span class="text-red-500">❤</span> for learners worldwide
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>
