// 15/news-hub/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { Category } from '../../models/news.model';
import { NewsService } from '../../services/news.service';

@Component({
  selector: 'app-footer',
  standalone: false,
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {
  categories: Category[] = [];
  currentYear: number = new Date().getFullYear();

  constructor(private newsService: NewsService) { }

  ngOnInit(): void {
    this.newsService.getCategories().subscribe(categories => {
      this.categories = categories;
    });
  }
}

<footer class="bg-secondary-800 text-white mt-16">
  <div class="container mx-auto px-4 py-12">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
      <div class="lg:col-span-1">
        <a routerLink="/" class="flex items-center space-x-2 mb-4">
          <div class="w-8 h-8 bg-primary-500 rounded-lg flex items-center justify-center">
            <span class="text-white font-bold text-lg">N</span>
          </div>
          <span class="text-xl font-bold">NewsHub</span>
        </a>
        <p class="text-secondary-300 text-sm leading-relaxed mb-4">
          提供最新、最全面的新闻资讯，让您随时了解世界动态。
        </p>
        <div class="flex space-x-4">
          <a href="#" class="text-secondary-300 hover:text-white transition-colors">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
            </svg>
          </a>
          <a href="#" class="text-secondary-300 hover:text-white transition-colors">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M22.675 0h-21.35c-.732 0-1.325.593-1.325 1.325v21.351c0 .731.593 1.324 1.325 1.324h11.495v-9.294h-3.128v-3.622h3.128v-2.671c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.795.143v3.24l-1.918.001c-1.504 0-1.795.715-1.795 1.763v2.313h3.587l-.467 3.622h-3.12v9.293h6.116c.73 0 1.323-.593 1.323-1.325v-21.35c0-.732-.593-1.325-1.325-1.325z"></path>
            </svg>
          </a>
          <a href="#" class="text-secondary-300 hover:text-white transition-colors">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"></path>
            </svg>
          </a>
        </div>
      </div>

      <div>
        <h3 class="text-lg font-semibold mb-4">新闻分类</h3>
        <ul class="space-y-2">
          <li *ngFor="let category of categories">
            <a 
              [routerLink]="['/category', category.id]"
              class="text-secondary-300 hover:text-white transition-colors text-sm flex items-center space-x-2"
            >
              <span>{{ category.icon }}</span>
              <span>{{ category.name }}</span>
            </a>
          </li>
        </ul>
      </div>

      <div>
        <h3 class="text-lg font-semibold mb-4">关于我们</h3>
        <ul class="space-y-2">
          <li>
            <a routerLink="/about" class="text-secondary-300 hover:text-white transition-colors text-sm">
              公司简介
            </a>
          </li>
          <li>
            <a routerLink="/contact" class="text-secondary-300 hover:text-white transition-colors text-sm">
              联系我们
            </a>
          </li>
          <li>
            <a href="#" class="text-secondary-300 hover:text-white transition-colors text-sm">
              加入我们
            </a>
          </li>
          <li>
            <a href="#" class="text-secondary-300 hover:text-white transition-colors text-sm">
              广告合作
            </a>
          </li>
        </ul>
      </div>

      <div>
        <h3 class="text-lg font-semibold mb-4">订阅新闻</h3>
        <p class="text-secondary-300 text-sm mb-4">
          订阅我们的新闻通讯，获取最新资讯推送。
        </p>
        <form class="flex flex-col space-y-2">
          <input 
            type="email" 
            placeholder="输入您的邮箱"
            class="px-4 py-2 bg-secondary-700 border border-secondary-600 rounded-lg text-white placeholder-secondary-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent text-sm"
          />
          <button 
            type="button"
            class="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-medium text-sm flex items-center justify-center"
          >
            订阅
          </button>
        </form>
      </div>
    </div>

    <div class="border-t border-secondary-700 mt-8 pt-8 flex flex-col md:flex-row justify-between items-center">
      <p class="text-secondary-400 text-sm">
        © {{ currentYear }} NewsHub. 保留所有权利。
      </p>
      <div class="flex space-x-6 mt-4 md:mt-0">
        <a href="#" class="text-secondary-400 hover:text-white transition-colors text-sm">
          隐私政策
        </a>
        <a href="#" class="text-secondary-400 hover:text-white transition-colors text-sm">
          使用条款
        </a>
        <a href="#" class="text-secondary-400 hover:text-white transition-colors text-sm">
          Cookie 政策
        </a>
      </div>
    </div>
  </div>
</footer>

// 7/avana-llc/src/components/Footer.tsx
import { Link } from 'react-router-dom';
import { 
  Mail, 
  Phone, 
  MapPin, 
  ArrowRight
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface FooterLink {
  label: string;
  path: string;
}

interface FooterColumn {
  title: string;
  links: FooterLink[];
}

const footerLinks: FooterColumn[] = [
  {
    title: '快速链接',
    links: [
      { label: '首页', path: '/' },
      { label: '关于我们', path: '/about' },
      { label: '作品集', path: '/portfolio/web-design' },
      { label: '博客', path: '/blog' },
      { label: '联系我们', path: '/contact' }
    ]
  },
  {
    title: '服务项目',
    links: [
      { label: '网页设计', path: '/services/web-design' },
      { label: '品牌设计', path: '/services/brand-design' },
      { label: 'UI/UX设计', path: '/services/ui-ux-design' },
      { label: '前端开发', path: '/services/frontend-development' }
    ]
  },
  {
    title: '法律条款',
    links: [
      { label: '隐私政策', path: '/privacy-policy' },
      { label: '服务条款', path: '/terms-of-service' },
      { label: 'Cookie政策', path: '/cookie-policy' }
    ]
  }
];

const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-gray-900 text-gray-300">
      {/* Main Footer */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12">
          {/* Brand Column */}
          <div className="lg:col-span-1">
            <Link to="/" className="flex items-center gap-2 mb-6">
              <div className="w-10 h-10 bg-primary rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-xl">A</span>
              </div>
              <span className="text-xl font-bold text-white">
                Avana <span className="text-primary">LLC</span>
              </span>
            </Link>
            <p className="text-gray-400 mb-6 leading-relaxed">
              我们是一家专注于创意设计和数字体验的专业团队。致力于为客户打造独特、现代且具有影响力的品牌形象和数字产品。
            </p>
            
            {/* Contact Info */}
            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <MapPin className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span className="text-sm">
                  上海市浦东新区陆家嘴金融中心<br />
                  环球金融中心 28楼
                </span>
              </div>
              <div className="flex items-center gap-3">
                <Phone className="w-5 h-5 text-primary shrink-0" />
                <span className="text-sm">+86 21 8888 8888</span>
              </div>
              <div className="flex items-center gap-3">
                <Mail className="w-5 h-5 text-primary shrink-0" />
                <span className="text-sm">hello@avana-llc.com</span>
              </div>
            </div>
          </div>

          {/* Links Columns */}
          {footerLinks.map((column) => (
            <div key={column.title}>
              <h3 className="text-white font-semibold text-lg mb-6">{column.title}</h3>
              <ul className="space-y-3">
                {column.links.map((link) => (
                  <li key={link.path}>
                    <Link
                      to={link.path}
                      className={cn(
                        "inline-flex items-center gap-2 text-gray-400 hover:text-primary transition-colors group",
                        "text-sm"
                      )}
                    >
                      <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all" />
                      <span>{link.label}</span>
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Newsletter Section */}
        <div className="mt-16 pt-12 border-t border-gray-800">
          <div className="flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="max-w-md">
              <h3 className="text-white font-semibold text-xl mb-2">订阅我们的通讯</h3>
              <p className="text-gray-400 text-sm">
                获取最新的设计趋势、行业洞察和公司动态。
              </p>
            </div>
            <div className="w-full md:w-auto">
              <form className="flex flex-col sm:flex-row gap-3">
                <input
                  type="email"
                  placeholder="输入您的邮箱地址"
                  className="flex-1 min-w-[240px] px-4 py-3 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-colors"
                />
                <button
                  type="submit"
                  className="px-6 py-3 bg-primary text-white font-medium rounded-lg hover:bg-primary-dark transition-colors whitespace-nowrap flex items-center justify-center gap-2"
                >
                  <span>订阅</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Footer */}
      <div className="border-t border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            {/* Copyright */}
            <p className="text-gray-500 text-sm">
              © {currentYear} Avana LLC. 保留所有权利。
            </p>

            {/* Social Links */}
            <div className="flex items-center gap-4">
              <a
                href="#"
                className="w-10 h-10 bg-gray-800 rounded-lg flex items-center justify-center text-gray-400 hover:bg-primary hover:text-white transition-all"
                aria-label="Facebook"
              >
                <span className="text-xs font-bold">f</span>
              </a>
              <a
                href="#"
                className="w-10 h-10 bg-gray-800 rounded-lg flex items-center justify-center text-gray-400 hover:bg-primary hover:text-white transition-all"
                aria-label="Twitter"
              >
                <span className="text-xs font-bold">X</span>
              </a>
              <a
                href="#"
                className="w-10 h-10 bg-gray-800 rounded-lg flex items-center justify-center text-gray-400 hover:bg-primary hover:text-white transition-all"
                aria-label="Instagram"
              >
                <span className="text-xs font-bold">in</span>
              </a>
              <a
                href="#"
                className="w-10 h-10 bg-gray-800 rounded-lg flex items-center justify-center text-gray-400 hover:bg-primary hover:text-white transition-all"
                aria-label="LinkedIn"
              >
                <span className="text-xs font-bold">Li</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
