// 15/racing-game/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { GameService } from '../../services/game.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, NzButtonModule, NzCardModule, NzIconModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent implements OnInit {
  highScore = 0;

  constructor(
    private router: Router,
    private gameService: GameService
  ) {}

  ngOnInit(): void {
    this.gameService.gameState$.subscribe(state => {
      this.highScore = state.highScore;
    });
  }

  startGame(): void {
    this.gameService.resetGame();
    this.router.navigate(['/game']);
  }
}

<div class="min-h-screen bg-gradient-to-b from-racing-dark via-racing-blue to-racing-dark flex flex-col items-center justify-center p-4">
  <div class="text-center mb-8">
    <div class="text-6xl mb-4">🏎️</div>
    <h1 class="text-5xl font-bold text-white mb-2 tracking-wider">
      <span class="text-racing-red">RACING</span>
      <span class="text-racing-yellow">GAME</span>
    </h1>
    <p class="text-gray-300 text-lg">高速赛道 · 极限挑战</p>
  </div>

  <nz-card class="w-full max-w-md bg-white/10 backdrop-blur-sm border-none shadow-2xl">
    <div class="flex flex-col gap-6">
      <div class="text-center">
        <p class="text-gray-400 text-sm mb-1">HIGH SCORE</p>
        <p class="text-4xl font-bold text-racing-yellow">{{ highScore }}</p>
      </div>

      <button
        nz-button
        nzType="primary"
        nzSize="large"
        (click)="startGame()"
        class="h-16 text-xl font-bold bg-gradient-to-r from-racing-red to-red-600 hover:from-red-500 hover:to-red-700 border-none shadow-lg shadow-racing-red/30 transform transition-all duration-300 hover:scale-105 active:scale-95"
      >
        <span nz-icon nzType="play-circle" nzTheme="outline" class="mr-2"></span>
        开始游戏
      </button>

      <div class="bg-white/5 rounded-lg p-4">
        <h3 class="text-white font-bold mb-3 flex items-center gap-2">
          <span nz-icon nzType="info-circle" nzTheme="outline" class="text-racing-blue"></span>
          游戏说明
        </h3>
        <ul class="text-gray-300 text-sm space-y-2">
          <li class="flex items-start gap-2">
            <span nz-icon nzType="arrow-left" class="text-racing-green mt-0.5"></span>
            <span>使用 <kbd class="bg-gray-700 px-2 py-0.5 rounded text-xs">←</kbd> <kbd class="bg-gray-700 px-2 py-0.5 rounded text-xs">→</kbd> 方向键或点击按钮控制赛车左右移动</span>
          </li>
          <li class="flex items-start gap-2">
            <span nz-icon nzType="car" class="text-racing-red mt-0.5"></span>
            <span>躲避前方驶来的车辆</span>
          </li>
          <li class="flex items-start gap-2">
            <span nz-icon nzType="heart" class="text-red-400 mt-0.5"></span>
            <span>你有 3 条命，碰撞会减少生命</span>
          </li>
          <li class="flex items-start gap-2">
            <span nz-icon nzType="trophy" class="text-racing-yellow mt-0.5"></span>
            <span>坚持越久，分数越高，难度也会增加</span>
          </li>
        </ul>
      </div>
    </div>
  </nz-card>

  <footer class="mt-8 text-gray-500 text-sm">
    <p>使用 Angular + Tailwind CSS + NG-ZORRO 构建</p>
  </footer>
</div>

// 7/tank-battle-game/src/pages/Home.tsx
import React from 'react'
import { Button, Card, Typography } from 'antd'
import { useNavigate } from 'react-router-dom'
import { PlayCircleOutlined, InfoCircleOutlined } from '@ant-design/icons'

const { Title, Paragraph } = Typography

const Home: React.FC = () => {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-blue-900 to-gray-900 flex items-center justify-center p-4">
      <Card className="w-full max-w-3xl bg-gray-800/80 backdrop-blur-sm border-gray-700 shadow-2xl">
        <div className="text-center mb-8">
          <Title level={1} className="text-white font-bold mb-2 drop-shadow-lg">
            🎮 坦克大战
          </Title>
          <Paragraph className="text-gray-200 text-lg font-medium">
            经典坦克大战游戏，使用键盘控制坦克移动和射击
          </Paragraph>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <Card className="bg-gray-800/95 border-gray-500 shadow-lg">
            <Title level={4} className="text-yellow-400 font-bold flex items-center gap-2">
              <InfoCircleOutlined className="text-yellow-400 text-xl" /> 操作说明
            </Title>
            <div className="text-white space-y-3 mt-4">
              <p className="flex items-center gap-2"><span className="text-xl">⬆️</span> <span className="font-medium">上箭头键</span> - 向上移动</p>
              <p className="flex items-center gap-2"><span className="text-xl">⬇️</span> <span className="font-medium">下箭头键</span> - 向下移动</p>
              <p className="flex items-center gap-2"><span className="text-xl">⬅️</span> <span className="font-medium">左箭头键</span> - 向左移动</p>
              <p className="flex items-center gap-2"><span className="text-xl">➡️</span> <span className="font-medium">右箭头键</span> - 向右移动</p>
              <p className="flex items-center gap-2"><span className="text-xl">🔫</span> <span className="font-medium">空格键</span> - 发射炮弹</p>
            </div>
          </Card>

          <Card className="bg-gray-800/95 border-gray-500 shadow-lg">
            <Title level={4} className="text-green-400 font-bold">游戏目标</Title>
            <div className="text-white space-y-3 mt-4">
              <p className="flex items-center gap-2"><span className="text-xl">🎯</span> <span className="font-medium">消灭所有敌方坦克</span></p>
              <p className="flex items-center gap-2"><span className="text-xl">🏠</span> <span className="font-medium">保护基地不被摧毁</span></p>
              <p className="flex items-center gap-2"><span className="text-xl">💎</span> <span className="font-medium">收集道具提升能力</span></p>
              <p className="flex items-center gap-2"><span className="text-xl">🏆</span> <span className="font-medium">完成关卡获得胜利</span></p>
            </div>
          </Card>
        </div>

        <div className="text-center">
          <Button
            type="primary"
            size="large"
            icon={<PlayCircleOutlined />}
            onClick={() => navigate('/game')}
            className="h-16 text-xl px-12 bg-blue-600 hover:bg-blue-700 border-none"
          >
            开始游戏
          </Button>
        </div>
      </Card>
    </div>
  )
}

export default Home
