// 24/contemporary-dance-academy/src/components/Header.jsx
import { useState, useEffect } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { Button } from 'antd'
import {
  MenuOutlined,
  CloseOutlined,
  PhoneOutlined,
  MailOutlined,
} from '@ant-design/icons'

const navItems = [
  { key: '/', label: '首页', path: '/' },
  { key: '/classes', label: '课程', path: '/classes' },
  { key: '/schedule', label: '课表', path: '/schedule' },
  { key: '/about', label: '关于我们', path: '/about' },
]

const Header = () => {
  const [isScrolled, setIsScrolled] = useState(false)
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const location = useLocation()

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50)
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  useEffect(() => {
    setIsMobileMenuOpen(false)
  }, [location])

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled 
          ? 'bg-black/95 backdrop-blur-md shadow-lg shadow-pink-500/10' 
          : 'bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16 md:h-20">
          {/* Logo */}
          <Link to="/" className="flex items-center space-x-2 group">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-pink-500 to-pink-700 flex items-center justify-center transition-transform group-hover:scale-110">
              <span className="text-white font-bold text-lg">舞</span>
            </div>
            <div className="flex flex-col">
              <span className="text-white font-bold text-lg leading-tight">当代舞蹈学院</span>
              <span className="text-pink-400 text-xs tracking-wider">CONTEMPORARY DANCE</span>
            </div>
          </Link>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-1">
            {navItems.map((item) => (
              <Link
                key={item.key}
                to={item.path}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-all duration-300 ${
                  location.pathname === item.path
                    ? 'text-pink-400 bg-pink-500/10'
                    : 'text-gray-300 hover:text-pink-400 hover:bg-pink-500/5'
                }`}
              >
                {item.label}
              </Link>
            ))}
            <div className="ml-4 pl-4 border-l border-gray-700">
              <Link to="/schedule">
                <Button
                  type="primary"
                  size="large"
                  className="h-10 px-6 font-medium bg-gradient-to-r from-pink-500 to-pink-600 hover:from-pink-600 hover:to-pink-700 shadow-lg shadow-pink-500/30 transition-all hover:shadow-pink-500/50"
                >
                  预约课程
                </Button>
              </Link>
            </div>
          </nav>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="md:hidden p-2 rounded-lg text-gray-300 hover:text-pink-400 hover:bg-pink-500/10 transition-colors"
          >
            {isMobileMenuOpen ? <CloseOutlined style={{ fontSize: '24px' }} /> : <MenuOutlined style={{ fontSize: '24px' }} />}
          </button>
        </div>
      </div>

      {/* Mobile Menu */}
      {isMobileMenuOpen && (
        <div className="md:hidden bg-black/98 backdrop-blur-md border-t border-gray-800">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 space-y-1">
            {navItems.map((item) => (
              <Link
                key={item.key}
                to={item.path}
                className={`block px-4 py-3 rounded-lg text-base font-medium transition-all duration-300 ${
                  location.pathname === item.path
                    ? 'text-pink-400 bg-pink-500/10'
                    : 'text-gray-300 hover:text-pink-400 hover:bg-pink-500/5'
                }`}
              >
                {item.label}
              </Link>
            ))}
            <div className="pt-4 mt-4 border-t border-gray-800">
              <Link to="/schedule" className="block">
                <Button
                  type="primary"
                  size="large"
                  className="w-full h-12 px-6 font-medium bg-gradient-to-r from-pink-500 to-pink-600"
                >
                  预约课程
                </Button>
              </Link>
            </div>
            <div className="pt-4 space-y-3 text-sm text-gray-400">
              <div className="flex items-center space-x-2">
                <PhoneOutlined className="text-pink-400" />
                <span>400-888-9999</span>
              </div>
              <div className="flex items-center space-x-2">
                <MailOutlined className="text-pink-400" />
                <span>info@dance-academy.com</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </header>
  )
}

export default Header

// 6/digital-magazine/src/components/Header.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'

const router = useRouter()
const route = useRoute()
const isScrolled = ref(false)
const isMobileMenuOpen = ref(false)

const navItems = [
  { name: '首页', path: '/' },
  { name: '杂志', path: '/magazine' },
  { name: '关于', path: '/about' }
]

const handleScroll = () => {
  isScrolled.value = window.scrollY > 50
}

const toggleMobileMenu = () => {
  isMobileMenuOpen.value = !isMobileMenuOpen.value
}

const navigateTo = (path: string) => {
  isMobileMenuOpen.value = false
  router.push(path)
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<template>
  <header 
    :class="[
      'fixed top-0 left-0 right-0 z-50 transition-all duration-300',
      isScrolled ? 'bg-white/95 backdrop-blur-md shadow-md py-3' : 'bg-transparent py-5'
    ]"
  >
    <div class="max-w-6xl mx-auto px-4">
      <div class="flex justify-between items-center">
        <!-- Logo -->
        <div class="flex items-center cursor-pointer" @click="navigateTo('/')">
          <div class="w-10 h-10 bg-gradient-to-br from-primary-500 to-accent-500 rounded-lg flex items-center justify-center mr-3">
            <span class="text-white font-bold text-xl">M</span>
          </div>
          <span class="text-2xl font-display font-bold" :class="isScrolled ? 'text-gray-800' : 'text-white'">
            Digital <span class="text-primary-500">Magazine</span>
          </span>
        </div>
        
        <!-- Desktop Navigation -->
        <nav class="hidden md:flex items-center space-x-8">
          <a 
            v-for="item in navItems" 
            :key="item.path"
            @click="navigateTo(item.path)"
            :class="[
              'font-medium transition-colors duration-200 cursor-pointer',
              route.path === item.path 
                ? 'text-primary-600 font-semibold' 
                : isScrolled ? 'text-gray-700 hover:text-primary-500' : 'text-white/90 hover:text-white'
            ]"
          >
            {{ item.name }}
          </a>
        </nav>
        
        <!-- Mobile Menu Button -->
        <button 
          class="md:hidden p-2 rounded-lg transition-colors"
          :class="isScrolled ? 'text-gray-700 hover:bg-gray-100' : 'text-white hover:bg-white/10'"
          @click="toggleMobileMenu"
        >
          <svg v-if="!isMobileMenuOpen" class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
          <svg v-else class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
      </div>
      
      <!-- Mobile Menu -->
      <div 
        :class="[
          'md:hidden transition-all duration-300 overflow-hidden',
          isMobileMenuOpen ? 'max-h-64 opacity-100 mt-4' : 'max-h-0 opacity-0'
        ]"
      >
        <nav class="flex flex-col space-y-3 py-4">
          <a 
            v-for="item in navItems" 
            :key="item.path"
            @click="navigateTo(item.path)"
            :class="[
              'font-medium py-2 px-4 rounded-lg transition-colors duration-200 cursor-pointer',
              route.path === item.path 
                ? 'bg-primary-100 text-primary-700' 
                : 'text-gray-700 hover:bg-gray-100'
            ]"
          >
            {{ item.name }}
          </a>
        </nav>
      </div>
    </div>
  </header>
</template>

<style scoped>
</style>
