// 3/coursespace-angular/src/app/components/hero/hero.component.ts
import { Component } from '@angular/core';
import { Stat } from '../../models/types';
import { STATS } from '../../data/mock-data';

@Component({
  selector: 'app-hero',
  standalone: false,
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.css']
})
export class HeroComponent {
  stats: Stat[] = STATS;

  scrollToCourses(): void {
    const element = document.getElementById('courses');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  }

  watchVideo(): void {
    console.log('Opening video modal...');
  }
}

<section id="hero" class="min-h-screen pt-20 relative overflow-hidden bg-gradient-to-br from-gray-50 via-white to-primary-50 dark:from-dark-bg dark:via-dark-bg dark:to-gray-900">
  <div class="absolute inset-0 opacity-10">
    <div class="absolute top-20 left-10 w-72 h-72 bg-primary-300 rounded-full mix-blend-multiply filter blur-3xl animate-pulse-slow"></div>
    <div class="absolute top-40 right-10 w-72 h-72 bg-secondary-300 rounded-full mix-blend-multiply filter blur-3xl animate-pulse-slow" style="animation-delay: 1s;"></div>
    <div class="absolute bottom-20 left-1/3 w-72 h-72 bg-accent-300 rounded-full mix-blend-multiply filter blur-3xl animate-pulse-slow" style="animation-delay: 2s;"></div>
  </div>

  <div class="container-custom mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
    <div class="grid lg:grid-cols-2 gap-12 items-center min-h-[calc(100vh-80px)] py-12">
      <div class="space-y-8">
        <div class="inline-flex items-center space-x-2 bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 px-4 py-2 rounded-full text-sm font-medium">
          <span nz-icon nzType="rocket" nzTheme="outline"></span>
          <span>Start Learning Today</span>
        </div>

        <h1 class="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white leading-tight">
          Learn Anytime,
          <br />
          <span class="relative inline-block">
            Anywhere
            <svg class="absolute -bottom-2 left-0 w-full" viewBox="0 0 200 12" fill="none">
              <path d="M2 10C40 2 80 2 100 6C120 10 160 10 198 2" stroke="url(#underline)" stroke-width="4" stroke-linecap="round"/>
              <defs>
                <linearGradient id="underline" x1="0" y1="0" x2="200" y2="0">
                  <stop stop-color="#3b82f6"/>
                  <stop offset="1" stop-color="#22c55e"/>
                </linearGradient>
              </defs>
            </svg>
          </span>
          <br />
          <span class="bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent">
            Upskill Your Career
          </span>
        </h1>

        <p class="text-lg text-gray-600 dark:text-gray-300 max-w-xl leading-relaxed">
          Join thousands of students worldwide and transform your career with our expert-led online courses. Learn at your own pace with lifetime access.
        </p>

        <div class="flex flex-wrap gap-4">
          <button 
            (click)="scrollToCourses()"
            class="inline-flex items-center space-x-2 bg-gradient-to-r from-primary-600 to-primary-700 hover:from-primary-700 hover:to-primary-800 text-white font-semibold py-4 px-8 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 active:scale-95"
          >
            <span>Get Started</span>
            <span nz-icon nzType="arrow-right" nzTheme="outline"></span>
          </button>

          <button 
            (click)="watchVideo()"
            class="inline-flex items-center space-x-3 text-gray-700 dark:text-gray-200 font-semibold py-4 px-6 hover:text-primary-600 dark:hover:text-primary-400 transition-colors duration-300"
          >
            <span class="w-12 h-12 bg-white dark:bg-gray-800 rounded-full flex items-center justify-center shadow-lg hover:shadow-xl transition-all duration-300">
              <span nz-icon nzType="play-circle" nzTheme="fill" class="text-primary-600 text-xl"></span>
            </span>
            <span>Watch Video</span>
          </button>
        </div>

        <div class="grid grid-cols-3 gap-6 pt-8 border-t border-gray-200 dark:border-gray-800">
          @for (stat of stats; track stat.id) {
            <div class="text-center">
              <div class="text-3xl sm:text-4xl font-bold bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent">
                {{ stat.value }}
              </div>
              <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">
                {{ stat.label }}
              </div>
            </div>
          }
        </div>
      </div>

      <div class="relative lg:pl-12">
        <div class="relative">
          <img 
            src="https://picsum.photos/seed/hero-main/600/500" 
            alt="Online Learning"
            class="w-full rounded-3xl shadow-2xl"
          />
          
          <div class="absolute -top-4 -left-4 sm:-left-8 bg-white dark:bg-gray-800 rounded-2xl p-4 shadow-xl flex items-center space-x-3 animate-fade-in">
            <div class="w-12 h-12 bg-secondary-100 dark:bg-secondary-900/30 rounded-xl flex items-center justify-center">
              <span nz-icon nzType="trophy" nzTheme="fill" class="text-secondary-600 text-xl"></span>
            </div>
            <div>
              <div class="font-semibold text-gray-900 dark:text-white">Award Winner</div>
              <div class="text-sm text-gray-500 dark:text-gray-400">2024 Best Platform</div>
            </div>
          </div>

          <div class="absolute -bottom-4 -right-4 sm:-right-8 bg-white dark:bg-gray-800 rounded-2xl p-4 shadow-xl flex items-center space-x-3">
            <div class="w-12 h-12 bg-primary-100 dark:bg-primary-900/30 rounded-xl flex items-center justify-center">
              <span nz-icon nzType="star" nzTheme="fill" class="text-primary-600 text-xl"></span>
            </div>
            <div>
              <div class="font-semibold text-gray-900 dark:text-white">4.9/5 Rating</div>
              <div class="text-sm text-gray-500 dark:text-gray-400">15,000+ Reviews</div>
            </div>
          </div>

          <div class="absolute top-1/2 -right-2 sm:-right-6 transform -translate-y-1/2">
            <div class="bg-white dark:bg-gray-800 rounded-2xl p-4 shadow-xl w-40">
              <div class="flex items-center justify-center space-x-1 mb-2">
                <span nz-icon nzType="check-circle" nzTheme="fill" class="text-secondary-500"></span>
                <span class="text-xs text-gray-600 dark:text-gray-400">Certified Courses</span>
              </div>
              <div class="flex -space-x-2">
                <div class="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 border-2 border-white dark:border-gray-800 overflow-hidden">
                  <img src="https://picsum.photos/seed/cert1/40/40" alt="Certificate" class="w-full h-full object-cover">
                </div>
                <div class="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 border-2 border-white dark:border-gray-800 overflow-hidden">
                  <img src="https://picsum.photos/seed/cert2/40/40" alt="Certificate" class="w-full h-full object-cover">
                </div>
                <div class="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 border-2 border-white dark:border-gray-800 overflow-hidden">
                  <img src="https://picsum.photos/seed/cert3/40/40" alt="Certificate" class="w-full h-full object-cover">
                </div>
                <div class="w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-900/30 border-2 border-white dark:border-gray-800 flex items-center justify-center">
                  <span class="text-xs font-semibold text-primary-600">+50</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// playbox-gaming-console/src/components/Hero.tsx
import React, { useState, useEffect } from 'react';
import ImageWithFallback from '@/components/ImageWithFallback';

const Hero: React.FC = () => {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setIsLoaded(true);
  }, []);

  const handleBuyNow = () => {
    const element = document.getElementById('products');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const handleWatchDemo = () => {
    alert('Demo video would play here!');
  };

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
      <div 
        className="absolute inset-0 bg-cover bg-center bg-no-repeat"
        style={{
          backgroundImage: `linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 50%, #0f0f1a 100%), url('https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dark%20neon%20lit%20gaming%20room%20atmosphere%20with%20retro%20arcade%20machines%20and%20vibrant%20purple%20pink%20blue%20lights%20cinematic%20mood&image_size=landscape_16_9')`,
          backgroundBlendMode: 'overlay',
        }}
      />
      
      <div className="absolute inset-0 bg-gradient-to-br from-[var(--gaming-dark)]/90 via-[var(--gaming-purple)]/40 to-[var(--gaming-neon)]/30" />
      
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-[var(--gaming-neon)]/20 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-[var(--gaming-cyan)]/20 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1s' }} />
        <div className="absolute top-1/2 left-1/2 w-64 h-64 bg-[var(--gaming-purple)]/30 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '2s' }} />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div className={`text-center lg:text-left transition-all duration-1000 ${
            isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'
          }`}>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[var(--gaming-neon)]/10 border border-[var(--gaming-neon)]/30 mb-6">
              <span className="w-2 h-2 bg-[var(--gaming-neon)] rounded-full animate-pulse" />
              <span className="text-[var(--gaming-neon)] text-sm font-medium">
                New Release 2024
              </span>
            </div>

            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold mb-6">
              <span className="block text-[var(--gaming-light)] mb-2">
                Introducing
              </span>
              <span className="block bg-gradient-to-r from-[var(--gaming-neon)] via-[var(--gaming-cyan)] to-[var(--gaming-purple)] bg-clip-text text-transparent animate-pulse-gradient">
                PLAYBOX
              </span>
            </h1>

            <p className="text-lg md:text-xl text-[var(--gaming-muted)] mb-8 max-w-2xl mx-auto lg:mx-0">
              The ultimate portable gaming experience. Play 20,000+ classic retro games 
              anywhere, anytime. Stunning HD display, 8-hour battery life, and immersive 
              audio that brings your favorite games to life.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-4 mb-12">
              <button
                onClick={handleBuyNow}
                className="gaming-button w-full sm:w-auto flex items-center justify-center gap-2"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
                Buy Now - $199.99
              </button>
              
              <button
                onClick={handleWatchDemo}
                className="gaming-button-outline w-full sm:w-auto flex items-center justify-center gap-2"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Watch Demo
              </button>
            </div>

            <div className="grid grid-cols-3 gap-4">
              <div className="text-center">
                <div className="text-2xl md:text-3xl font-bold text-[var(--gaming-neon)]">
                  20K+
                </div>
                <div className="text-sm text-[var(--gaming-muted)]">Games</div>
              </div>
              <div className="text-center border-x border-[var(--gaming-muted)]/30">
                <div className="text-2xl md:text-3xl font-bold text-[var(--gaming-cyan)]">
                  8H
                </div>
                <div className="text-sm text-[var(--gaming-muted)]">Battery</div>
              </div>
              <div className="text-center">
                <div className="text-2xl md:text-3xl font-bold text-[var(--gaming-purple)]">
                  4.9★
                </div>
                <div className="text-sm text-[var(--gaming-muted)]">Rating</div>
              </div>
            </div>
          </div>

          <div className={`relative flex items-center justify-center transition-all duration-1000 delay-300 ${
            isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'
          }`}>
            <div className="relative">
              <div className="absolute -inset-8 bg-gradient-to-r from-[var(--gaming-neon)] via-[var(--gaming-cyan)] to-[var(--gaming-purple)] rounded-3xl blur-3xl opacity-50 animate-pulse" />
              
              <div className="relative animate-float">
                <ImageWithFallback
                  src="https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=sleek%20modern%20portable%20handheld%20gaming%20console%20PLAYBOX%20with%20neon%20pink%20purple%20blue%20lighting%20effects%20on%20dark%20background%20product%20photography%20high%20quality%20render&image_size=square_hd"
                  alt="PLAYBOX Portable Gaming Console"
                  className="w-80 h-80 md:w-96 md:h-96 rounded-2xl"
                  fallbackContent={
                    <div className="w-full h-full rounded-2xl bg-gradient-to-br from-[var(--gaming-dark)] to-[var(--gaming-dark-secondary)] flex items-center justify-center border-2 border-dashed border-[var(--gaming-neon)]/30">
                      <div className="text-center">
                        <div className="text-6xl mb-4">🎮</div>
                        <div className="text-xl font-bold text-[var(--gaming-light)]">PLAYBOX</div>
                        <div className="text-sm text-[var(--gaming-muted)]">Portable Gaming Console</div>
                      </div>
                    </div>
                  }
                />
                
                <div className="absolute -bottom-4 left-1/2 transform -translate-x-1/2">
                  <div className="flex items-center gap-2 px-4 py-2 bg-[var(--gaming-dark)]/80 backdrop-blur-sm rounded-full border border-[var(--gaming-neon)]/30">
                    <div className="flex -space-x-2">
                      {[1, 2, 3, 4].map((i) => (
                        <div
                          key={i}
                          className="w-8 h-8 rounded-full border-2 border-[var(--gaming-dark)] bg-gradient-to-br from-[var(--gaming-neon)] to-[var(--gaming-purple)] flex items-center justify-center text-xs font-bold"
                        >
                          {String.fromCharCode(64 + i)}
                        </div>
                      ))}
                    </div>
                    <span className="text-sm text-[var(--gaming-light)]">
                      <span className="font-bold text-[var(--gaming-neon)]">10K+</span> happy customers
                    </span>
                  </div>
                </div>
              </div>

              <div className="absolute -top-8 -right-8 animate-bounce" style={{ animationDelay: '0.5s' }}>
                <div className="w-16 h-16 bg-[var(--gaming-dark)] rounded-2xl border-2 border-[var(--gaming-neon)] flex items-center justify-center shadow-lg shadow-[var(--gaming-neon)]/20">
                  <span className="text-2xl">🎮</span>
                </div>
              </div>

              <div className="absolute -bottom-8 -left-8 animate-bounce" style={{ animationDelay: '1s' }}>
                <div className="w-16 h-16 bg-[var(--gaming-dark)] rounded-2xl border-2 border-[var(--gaming-cyan)] flex items-center justify-center shadow-lg shadow-[var(--gaming-cyan)]/20">
                  <span className="text-2xl">🔋</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
        <div className="flex flex-col items-center gap-2 text-[var(--gaming-muted)]">
          <span className="text-sm">Scroll to explore</span>
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
          </svg>
        </div>
      </div>
    </section>
  );
};

export default Hero;
