// medical-consultation-platform/src/components/layout/Navbar.jsx
import { Link, useLocation } from 'react-router-dom';
import {
  Home,
  Calendar,
  MessageCircle,
  FileText,
  Pill,
  User,
  AlertTriangle,
  Bell,
  Search,
  Menu,
  X,
} from 'lucide-react';
import { useState } from 'react';
import { cn } from '@/utils';
import { Avatar } from '@/components/ui/Avatar';

const navItems = [
  { path: '/', label: '首页', icon: Home },
  { path: '/appointment', label: '医生预约', icon: Calendar },
  { path: '/consultation', label: '在线问诊', icon: MessageCircle },
  { path: '/medical-records', label: '病历管理', icon: FileText },
  { path: '/medicines', label: '药品信息', icon: Pill },
  { path: '/health-records', label: '健康档案', icon: User },
  { path: '/emergency', label: '紧急求助', icon: AlertTriangle },
];

export const Navbar = () => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const location = useLocation();

  return (
    <nav className="bg-white border-b border-border sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center">
            <Link to="/" className="flex items-center space-x-2">
              <div className="w-10 h-10 bg-primary rounded-xl flex items-center justify-center">
                <Home className="w-6 h-6 text-white" />
              </div>
              <span className="text-xl font-bold text-text">
                智慧医疗
              </span>
            </Link>
          </div>

          <div className="hidden md:flex items-center space-x-1">
            {navItems.map((item) => {
              const Icon = item.icon;
              const isActive = location.pathname === item.path;
              return (
                <Link
                  key={item.path}
                  to={item.path}
                  className={cn(
                    'flex items-center space-x-1 px-3 py-2 rounded-lg text-sm font-medium transition-colors',
                    isActive
                      ? 'bg-primary/10 text-primary'
                      : 'text-text-secondary hover:bg-background hover:text-text'
                  )}
                >
                  <Icon className="w-4 h-4" />
                  <span>{item.label}</span>
                </Link>
              );
            })}
          </div>

          <div className="flex items-center space-x-4">
            <div className="hidden sm:flex items-center bg-background rounded-lg px-3 py-1.5">
              <Search className="w-4 h-4 text-text-secondary" />
              <input
                type="text"
                placeholder="搜索医生、药品..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="bg-transparent border-none outline-none ml-2 text-sm w-40"
              />
            </div>

            <button className="relative p-2 rounded-lg hover:bg-background transition-colors">
              <Bell className="w-5 h-5 text-text-secondary" />
              <span className="absolute top-1 right-1 w-2 h-2 bg-danger rounded-full"></span>
            </button>

            <div className="flex items-center space-x-2">
              <Avatar
                src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100&h=100"
                alt="用户头像"
                size="sm"
              />
              <div className="hidden lg:block">
                <p className="text-sm font-medium text-text">张三</p>
                <p className="text-xs text-text-secondary">普通用户</p>
              </div>
            </div>

            <button
              className="md:hidden p-2 rounded-lg hover:bg-background"
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            >
              {isMobileMenuOpen ? (
                <X className="w-5 h-5" />
              ) : (
                <Menu className="w-5 h-5" />
              )}
            </button>
          </div>
        </div>
      </div>

      {isMobileMenuOpen && (
        <div className="md:hidden bg-white border-t border-border">
          <div className="px-4 py-3 space-y-1">
            {navItems.map((item) => {
              const Icon = item.icon;
              const isActive = location.pathname === item.path;
              return (
                <Link
                  key={item.path}
                  to={item.path}
                  className={cn(
                    'flex items-center space-x-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors',
                    isActive
                      ? 'bg-primary/10 text-primary'
                      : 'text-text-secondary hover:bg-background hover:text-text'
                  )}
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  <Icon className="w-5 h-5" />
                  <span>{item.label}</span>
                </Link>
              );
            })}
          </div>
        </div>
      )}
    </nav>
  );
};

// mind-grow-encg/src/components/Navbar.vue
<template>
  <nav class="bg-white shadow-md sticky top-0 z-50">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center h-16">
        <!-- Logo -->
        <router-link to="/" class="flex items-center space-x-2">
          <div class="w-10 h-10 bg-gradient-to-br from-primary-500 to-secondary-600 rounded-xl flex items-center justify-center">
            <el-icon class="text-white text-xl"><Brain /></el-icon>
          </div>
          <span class="text-xl font-bold bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent">
            Mind & Grow ENCG
          </span>
        </router-link>

        <!-- Desktop Navigation -->
        <div class="hidden md:flex items-center space-x-1">
          <router-link
            v-for="link in navLinks"
            :key="link.path"
            :to="link.path"
            class="px-3 py-2 rounded-lg text-gray-600 hover:text-primary-600 hover:bg-primary-50 transition-all duration-200 font-medium text-sm"
            :class="{ 'text-primary-600 bg-primary-50': isActive(link.path) }"
          >
            {{ link.name }}
          </router-link>
        </div>

        <!-- Right Side Actions -->
        <div class="hidden md:flex items-center space-x-3">
          <el-button type="primary" size="small" class="rounded-lg">
            <el-icon><User /></el-icon>
            Sign In
          </el-button>
        </div>

        <!-- Mobile Menu Button -->
        <button
          @click="mobileMenuOpen = !mobileMenuOpen"
          class="md:hidden p-2 rounded-lg hover:bg-gray-100 transition-colors"
        >
          <el-icon :size="24" v-if="!mobileMenuOpen"><Menu /></el-icon>
          <el-icon :size="24" v-else><Close /></el-icon>
        </button>
      </div>

      <!-- Mobile Navigation -->
      <transition name="slide-up">
        <div v-if="mobileMenuOpen" class="md:hidden pb-4">
          <div class="flex flex-col space-y-1">
            <router-link
              v-for="link in navLinks"
              :key="link.path"
              :to="link.path"
              @click="mobileMenuOpen = false"
              class="px-4 py-3 rounded-lg text-gray-600 hover:text-primary-600 hover:bg-primary-50 transition-all duration-200 font-medium flex items-center space-x-3"
              :class="{ 'text-primary-600 bg-primary-50': isActive(link.path) }"
            >
              <el-icon><component :is="link.icon" /></el-icon>
              <span>{{ link.name }}</span>
            </router-link>
            <div class="pt-3">
              <el-button type="primary" size="default" class="w-full rounded-lg">
                <el-icon><User /></el-icon>
                Sign In
              </el-button>
            </div>
          </div>
        </div>
      </transition>
    </div>
  </nav>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const mobileMenuOpen = ref(false)

const navLinks = [
  { name: 'Home', path: '/', icon: 'HomeFilled' },
  { name: 'Health & Balance', path: '/health-balance', icon: 'Heart' },
  { name: 'Student Recipes', path: '/student-recipes', icon: 'KnifeFork' },
  { name: 'Community', path: '/community', icon: 'User' },
  { name: 'Well-Being Store', path: '/store', icon: 'ShoppingBag' },
  { name: 'Zen Studio', path: '/zen-studio', icon: 'VideoCamera' }
]

const isActive = (path) => {
  return route.path === path
}
</script>

<style scoped>
</style>
