// samet-portfolio/src/components/Header.tsx
import React, { useState, useEffect } from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { useTheme } from '../contexts/ThemeContext';
import { Sun, Moon, Menu, X, Globe } from 'lucide-react';
import VisitorCounter from './VisitorCounter';

const Header: React.FC = () => {
  const { language, setLanguage, t } = useLanguage();
  const { theme, toggleTheme } = useTheme();
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
    setIsMobileMenuOpen(false);
  };

  const navItems = [
    { id: 'about', label: t.nav.about },
    { id: 'experience', label: t.nav.experience },
    { id: 'projects', label: t.nav.projects },
    { id: 'skills', label: t.nav.skills },
    { id: 'contact', label: t.nav.contact },
  ];

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled
          ? 'bg-white/70 dark:bg-black/30 backdrop-blur-lg border-b border-black/10 dark:border-white/10'
          : 'bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <div className="flex-shrink-0">
            <span className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
              SS
            </span>
          </div>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-8">
            {navItems.map((item) => (
              <button
                key={item.id}
                onClick={() => scrollToSection(item.id)}
                className="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-white transition-colors duration-200 text-sm font-medium"
              >
                {item.label}
              </button>
            ))}
          </nav>

          {/* Right side controls */}
          <div className="hidden md:flex items-center space-x-4">
            <VisitorCounter />
            
            {/* Language Toggle */}
            <button
              onClick={() => setLanguage(language === 'en' ? 'tr' : 'en')}
              className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-white hover:bg-white/70 dark:hover:bg-white/20 transition-all duration-200"
            >
              <Globe size={16} />
              <span className="text-sm font-medium">{language.toUpperCase()}</span>
            </button>

            {/* Theme Toggle */}
            <button
              onClick={toggleTheme}
              className="p-2 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-white hover:bg-white/70 dark:hover:bg-white/20 transition-all duration-200"
            >
              {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
            </button>
          </div>

          {/* Mobile menu button */}
          <button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="md:hidden p-2 rounded-lg text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-white"
          >
            {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>
      </div>

      {/* Mobile Menu */}
      {isMobileMenuOpen && (
        <div className="md:hidden bg-white/90 dark:bg-black/80 backdrop-blur-lg border-t border-black/10 dark:border-white/10">
          <div className="px-4 py-4 space-y-3">
            {navItems.map((item) => (
              <button
                key={item.id}
                onClick={() => scrollToSection(item.id)}
                className="block w-full text-left px-4 py-2 text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-white hover:bg-black/5 dark:hover:bg-white/10 rounded-lg transition-colors"
              >
                {item.label}
              </button>
            ))}
            
            <div className="pt-4 border-t border-black/10 dark:border-white/10">
              <div className="flex items-center justify-between mb-4">
                <VisitorCounter />
              </div>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => setLanguage(language === 'en' ? 'tr' : 'en')}
                  className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200"
                >
                  <Globe size={16} />
                  <span className="text-sm">{language.toUpperCase()}</span>
                </button>
                <button
                  onClick={toggleTheme}
                  className="p-2 rounded-full bg-white/50 dark:bg-white/10 backdrop-blur-md border border-black/20 dark:border-white/20 text-gray-700 dark:text-gray-200"
                >
                  {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </header>
  );
};

export default Header;

// 3/coursespace-angular/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { NavItem } from '../../models/types';
import { NAV_ITEMS } from '../../data/mock-data';
import { ThemeService, Theme } from '../../services/theme.service';

@Component({
  selector: 'app-header',
  standalone: false,
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  navItems: NavItem[] = NAV_ITEMS;
  isDrawerOpen = false;
  currentTheme: Theme = 'light';

  constructor(private themeService: ThemeService) {}

  ngOnInit(): void {
    this.themeService.theme$.subscribe(theme => {
      this.currentTheme = theme;
    });
  }

  toggleDrawer(): void {
    this.isDrawerOpen = !this.isDrawerOpen;
  }

  closeDrawer(): void {
    this.isDrawerOpen = false;
  }

  toggleTheme(): void {
    this.themeService.toggleTheme();
  }

  scrollToSection(fragment: string): void {
    const element = document.getElementById(fragment);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
    this.closeDrawer();
  }
}

<header class="fixed top-0 left-0 right-0 z-40 bg-white/90 dark:bg-dark-bg/90 backdrop-blur-md border-b border-gray-100 dark:border-dark-border transition-colors duration-300">
  <div class="container-custom mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16 lg:h-20">
      <div class="flex items-center space-x-2">
        <div class="w-10 h-10 bg-gradient-to-br from-primary-500 to-secondary-500 rounded-xl flex items-center justify-center">
          <span class="text-white font-bold text-xl">C</span>
        </div>
        <span class="text-xl font-bold text-gray-900 dark:text-white">Coursespace</span>
      </div>

      <nav class="hidden lg:flex items-center space-x-8">
        @for (item of navItems; track item.id) {
          <button 
            (click)="scrollToSection(item.fragment)"
            class="text-gray-600 dark:text-gray-300 hover:text-primary-600 dark:hover:text-primary-400 font-medium transition-colors duration-200"
          >
            {{ item.label }}
          </button>
        }
      </nav>

      <div class="hidden lg:flex items-center space-x-4">
        <button
          (click)="toggleTheme()"
          class="p-2 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          nz-tooltip
          [nzTooltipTitle]="currentTheme === 'light' ? 'Switch to Dark Mode' : 'Switch to Light Mode'"
        >
          <span nz-icon [nzType]="currentTheme === 'light' ? 'moon' : 'sun'" nzTheme="outline" class="text-xl"></span>
        </button>

        <button class="text-gray-700 dark:text-gray-200 hover:text-primary-600 dark:hover:text-primary-400 font-medium transition-colors">
          Sign In
        </button>

        <button 
          nz-button
          nzType="primary"
          nzSize="large"
          class="bg-primary-600 hover:bg-primary-700 border-none rounded-lg px-6 py-2 font-medium transition-all shadow-md hover:shadow-lg"
        >
          Sign Up
        </button>
      </div>

      <button
        (click)="toggleDrawer()"
        class="lg:hidden p-2 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800"
      >
        <span nz-icon nzType="menu" nzTheme="outline" class="text-2xl"></span>
      </button>
    </div>
  </div>
</header>

@if (isDrawerOpen) {
  <div class="drawer-mask" (click)="closeDrawer()"></div>
}

<div class="drawer-content" [class.open]="isDrawerOpen">
  <div class="p-6">
    <div class="flex items-center justify-between mb-8">
      <div class="flex items-center space-x-2">
        <div class="w-8 h-8 bg-gradient-to-br from-primary-500 to-secondary-500 rounded-lg flex items-center justify-center">
          <span class="text-white font-bold">C</span>
        </div>
        <span class="text-lg font-bold text-gray-900 dark:text-white">Coursespace</span>
      </div>
      <button (click)="closeDrawer()" class="p-2 text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg">
        <span nz-icon nzType="close" nzTheme="outline" class="text-xl"></span>
      </button>
    </div>

    <nav class="flex flex-col space-y-4 mb-8">
      @for (item of navItems; track item.id) {
        <button 
          (click)="scrollToSection(item.fragment)"
          class="text-left text-gray-700 dark:text-gray-200 hover:text-primary-600 dark:hover:text-primary-400 font-medium text-lg py-2 border-b border-gray-100 dark:border-gray-800 transition-colors"
        >
          {{ item.label }}
        </button>
      }
    </nav>

    <div class="flex items-center justify-between py-4 border-b border-gray-100 dark:border-gray-800 mb-8">
      <span class="text-gray-700 dark:text-gray-200 font-medium">Theme</span>
      <button
        (click)="toggleTheme()"
        class="flex items-center space-x-2 px-3 py-2 bg-gray-100 dark:bg-gray-800 rounded-lg"
      >
        <span nz-icon [nzType]="currentTheme === 'light' ? 'sun' : 'moon'" nzTheme="outline"></span>
        <span class="text-sm">{{ currentTheme === 'light' ? 'Light' : 'Dark' }}</span>
      </button>
    </div>

    <div class="flex flex-col space-y-3">
      <button class="w-full py-3 text-gray-700 dark:text-gray-200 hover:text-primary-600 font-medium border-2 border-gray-200 dark:border-gray-700 rounded-lg transition-colors">
        Sign In
      </button>
      <button 
        nz-button
        nzType="primary"
        class="w-full py-6 bg-primary-600 hover:bg-primary-700 border-none rounded-lg font-medium shadow-md"
      >
        Sign Up
      </button>
    </div>
  </div>
</div>
