// developer-portfolio/src/components/Footer.jsx
import React from 'react';
import { FiGithub, FiTwitter, FiLinkedin, FiMail } from 'react-icons/fi';

const Footer = () => {
  const currentYear = new Date().getFullYear();

  const socialLinks = [
    { icon: FiGithub, href: 'https://github.com', label: 'GitHub' },
    { icon: FiTwitter, href: 'https://twitter.com', label: 'Twitter' },
    { icon: FiLinkedin, href: 'https://linkedin.com', label: 'LinkedIn' },
    { icon: FiMail, href: 'mailto:hello@example.com', label: 'Email' },
  ];

  return (
    <footer className="bg-gray-50 dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="flex flex-col md:flex-row justify-between items-center space-y-6 md:space-y-0">
          <div className="text-center md:text-left">
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
              Developer Portfolio
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm">
              Building digital experiences with passion and precision.
            </p>
          </div>

          <div className="flex items-center space-x-6">
            {socialLinks.map((link, index) => {
              const Icon = link.icon;
              return (
                <a
                  key={index}
                  href={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-600 dark:text-gray-400 hover:text-purple-600 dark:hover:text-purple-400 transition-colors duration-200"
                  aria-label={link.label}
                >
                  <Icon size={24} />
                </a>
              );
            })}
          </div>
        </div>

        <div className="mt-8 pt-8 border-t border-gray-200 dark:border-gray-800">
          <p className="text-center text-gray-500 dark:text-gray-500 text-sm">
            © {currentYear} Developer Portfolio. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// 2/restreamer-ui/src/app/shared/components/footer/footer.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: [],
  standalone: false
})
export class FooterComponent {
  @Input() version: string = '1.0.0';
  @Input() showLinks: boolean = true;
  
  currentYear: number = new Date().getFullYear();
  links = [
    { label: 'Documentation', url: '#' },
    { label: 'GitHub', url: '#' },
    { label: 'Support', url: '#' },
    { label: 'Privacy Policy', url: '#' },
    { label: 'Terms of Service', url: '#' }
  ];
}

<footer class="bg-white border-t border-gray-200 mt-auto">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    @if (showLinks && links.length > 0) {
      <div class="flex flex-wrap justify-center gap-6 mb-6">
        @for (link of links; track link.label) {
          <a 
            [href]="link.url" 
            class="text-sm text-gray-600 hover:text-blue-600 transition-colors"
          >
            {{ link.label }}
          </a>
        }
      </div>
      
      <div class="border-t border-gray-100 pt-6">
        <div class="flex flex-col sm:flex-row justify-between items-center gap-4">
          <div class="flex items-center gap-2">
            <i class="pi pi-video text-blue-500"></i>
            <span class="text-sm text-gray-600">
              Restreamer UI v{{ version }}
            </span>
          </div>
          
          <p class="text-sm text-gray-500">
            &copy; {{ currentYear }} Restreamer. All rights reserved.
          </p>
        </div>
      </div>
    } @else {
      <div class="flex flex-col sm:flex-row justify-between items-center gap-4">
        <div class="flex items-center gap-2">
          <i class="pi pi-video text-blue-500"></i>
          <span class="text-sm text-gray-600">
            Restreamer UI v{{ version }}
          </span>
        </div>
        
        <p class="text-sm text-gray-500">
          &copy; {{ currentYear }} Restreamer. All rights reserved.
        </p>
      </div>
    }
  </div>
</footer>
